/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.dokter;

import control.CustomerControl;
import control.TransaksiControl;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;
import model.Customer;
import model.Staf;
import model.Transaksi;

/**
 *
 * @author VICTUS
 */
public class PasienView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PeriksaView
     */
    TransaksiControl transaksiControl = new TransaksiControl();
    CustomerControl customerControl = new CustomerControl();
    Staf loginData = null;
    Customer pasien = null;
    Transaksi temp=null;
    int selectedId = 0;
    List<Transaksi> listTransaksi;
    
    public PasienView(Staf loginData) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        transaksiControl = new TransaksiControl();
        customerControl = new CustomerControl();
        this.loginData = loginData;
        showPasien();
        checkBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DiagnosisMenu = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaPasienLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        diagonosisInput = new javax.swing.JTextArea();
        umurPasienLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePasien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        checkBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DIAGNOSIS");

        namaPasienLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaPasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaPasienLabel.setText("Nama Pasien");

        diagonosisInput.setColumns(20);
        diagonosisInput.setRows(5);
        jScrollPane2.setViewportView(diagonosisInput);

        umurPasienLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        umurPasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        umurPasienLabel.setText("Umur Pasien");

        saveBtn.setText("Simpan");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(namaPasienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(umurPasienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(namaPasienLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umurPasienLabel)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(saveBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DiagnosisMenuLayout = new javax.swing.GroupLayout(DiagnosisMenu.getContentPane());
        DiagnosisMenu.getContentPane().setLayout(DiagnosisMenuLayout);
        DiagnosisMenuLayout.setHorizontalGroup(
            DiagnosisMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DiagnosisMenuLayout.setVerticalGroup(
            DiagnosisMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(null);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setForeground(new java.awt.Color(204, 204, 204));

        tablePasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePasien);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pilih Pasien Untuk Diperiksa");

        checkBtn.setText("Periksa");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(checkBtn)
                .addGap(46, 46, 46))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBtn))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Periksa "+pasien.getNama()+"? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
                namaPasienLabel.setText("Nama\t: "+pasien.getNama());
                umurPasienLabel.setText("Umur\t: "+Integer.toString(pasien.getUmur())+" Tahun");
                Transaksi t = new Transaksi(temp.getId(), temp.getTanggalTransaksi(), temp.getBiaya_klinik(), temp.getStatus(), temp.getKeluhan());
                transaksiControl.updateStatusDataTransaksi(t);
                DiagnosisMenu.setLocationRelativeTo(null);
                DiagnosisMenu.pack();
                DiagnosisMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                DiagnosisMenu.setVisible(true);
                break;
            case 1:
                break;
        }
    }//GEN-LAST:event_checkBtnActionPerformed

    private void tablePasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePasienMouseClicked
        // TODO add your handling code here:
        int clickedRow = tablePasien.getSelectedRow();
        TableModel tableModel =tablePasien.getModel();
        pasien = customerControl.searchCustomerByID(Integer.parseInt(tableModel.getValueAt(clickedRow, 8).toString()));
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 6).toString());
        String keluhan = tableModel.getValueAt(clickedRow, 3).toString();
        String tanggal = tableModel.getValueAt(clickedRow, 7).toString();
        temp = new Transaksi(selectedId, tanggal, 0, "Diperiksa", "");
        if(evt.getClickCount()==2 && tablePasien.getSelectedRow()!=-1){
            checkBtn.setEnabled(true);
            checkBtn.doClick();
        }else if(tablePasien.getSelectedRow()!=-1){
            checkBtn.setEnabled(true);
        }
    }//GEN-LAST:event_tablePasienMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        Transaksi t = new Transaksi(temp.getId(), temp.getTanggalTransaksi(), 50000, temp.getStatus(), diagonosisInput.getText());
        transaksiControl.updateStatusDataTransaksi(t);
        showPasien();
        DiagnosisMenu.dispose();
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame DiagnosisMenu;
    private javax.swing.JButton checkBtn;
    private javax.swing.JPanel container;
    private javax.swing.JTextArea diagonosisInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel namaPasienLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable tablePasien;
    private javax.swing.JLabel umurPasienLabel;
    // End of variables declaration//GEN-END:variables

    private void showPasien() {
        tablePasien.setModel(transaksiControl.showDataPasienPerDokter(loginData.getNama(), "Menunggu"));
    }
}
