/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.dokter;


import control.DetailTransaksiControl;
import control.ObatControl;
import control.TindakanControl;
import control.TransaksiControl;
import exception.InputKosongException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;
import listener.IButtonClickListener;
import model.DetailTransaksi;
import model.Obat;
import model.Staf;
import model.Tindakan;
import model.Transaksi;

/**
 *
 * @author VICTUS
 */
public class RawatView extends javax.swing.JInternalFrame {

    private DokterView dokterView;
    private IButtonClickListener listener;
    TransaksiControl transaksiControl = new TransaksiControl();
    DetailTransaksiControl detailTransaksiControl = new DetailTransaksiControl();
    ObatControl obatControl = new ObatControl();
    TindakanControl tindakanControl = new TindakanControl();
    //CustomerControl customerControl = new CustomerControl();
    Staf loginData = null;
    Transaksi transaksi = null;
    int selectedId = 0;
    List<Transaksi> listTransaksi;
    List<Obat> listObat;
    List<Tindakan> listTindakan;
    
    public RawatView(Staf loginData, DokterView dokterView) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        initRawatDataInput();
        this.listener = dokterView;
        this.dokterView = dokterView;
        this.loginData = loginData;
        transaksiControl = new TransaksiControl();
        detailTransaksiControl = new DetailTransaksiControl();
        obatControl = new ObatControl();
        tindakanControl = new TindakanControl();
        rawatBtn.setEnabled(false);
        showPasien();
        setObatDropdown();
        setTindakanDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RawatDataInput = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaPasienLabel = new javax.swing.JLabel();
        umurPasienLabel = new javax.swing.JLabel();
        diagnosisLabel = new javax.swing.JLabel();
        diagnosisInput = new javax.swing.JTextField();
        obatDropdown = new javax.swing.JComboBox<>();
        addObatBtn = new javax.swing.JButton();
        tindakanDropdown = new javax.swing.JComboBox<>();
        addTindakanBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jumlahObatInput = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableKeranjangObat = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableKeranjangTindakan = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePasien = new javax.swing.JTable();
        rawatBtn = new javax.swing.JButton();
        riwayatBtn = new javax.swing.JButton();

        RawatDataInput.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        RawatDataInput.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RawatDataInput.setLocation(new java.awt.Point(0, 0));
        RawatDataInput.setLocationByPlatform(true);
        RawatDataInput.setUndecorated(true);
        RawatDataInput.setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 102)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PERAWATAN");

        namaPasienLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaPasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaPasienLabel.setText("Nama Pasien");

        umurPasienLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        umurPasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        umurPasienLabel.setText("Umur Pasien");

        diagnosisLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        diagnosisLabel.setForeground(new java.awt.Color(0, 0, 0));
        diagnosisLabel.setText("Diagnosis      ");

        diagnosisInput.setPreferredSize(new java.awt.Dimension(648, 22));

        addObatBtn.setText("Tambah");
        addObatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObatBtnActionPerformed(evt);
            }
        });

        addTindakanBtn.setText("Tambah");
        addTindakanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTindakanBtnActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tindakan");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Obat");

        jumlahObatInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jumlahObatInput.setText("0");

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Batal");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        tableKeranjangObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableKeranjangObat);

        tableKeranjangTindakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tableKeranjangTindakan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cancelBtn)
                                .addGap(18, 18, 18)
                                .addComponent(okBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(obatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jumlahObatInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(addObatBtn))))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tindakanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addTindakanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(diagnosisLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(diagnosisInput, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(umurPasienLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaPasienLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, okBtn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(namaPasienLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umurPasienLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnosisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diagnosisInput, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tindakanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTindakanBtn)
                    .addComponent(obatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addObatBtn)
                    .addComponent(jumlahObatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(okBtn))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RawatDataInputLayout = new javax.swing.GroupLayout(RawatDataInput.getContentPane());
        RawatDataInput.getContentPane().setLayout(RawatDataInputLayout);
        RawatDataInputLayout.setHorizontalGroup(
            RawatDataInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RawatDataInputLayout.setVerticalGroup(
            RawatDataInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(null);
        setResizable(true);
        setFocusable(false);

        tablePasien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePasien.setRowHeight(40);
        tablePasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePasien);

        rawatBtn.setText("Rawat");
        rawatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawatBtnActionPerformed(evt);
            }
        });

        riwayatBtn.setText("Riwayat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rawatBtn)
                    .addComponent(riwayatBtn))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rawatBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(riwayatBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePasienMouseClicked
        // TODO add your handling code here:
        int clickedRow = tablePasien.getSelectedRow();
        TableModel tableModel =tablePasien.getModel();
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 6).toString());
        
        if(evt.getClickCount()==2 && tablePasien.getSelectedRow()!=-1){
            rawatBtn.setEnabled(true);
            rawatBtn.doClick();
        }else if(tablePasien.getSelectedRow()!=-1){
            rawatBtn.setEnabled(true);
        }
    }//GEN-LAST:event_tablePasienMouseClicked

    private void rawatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawatBtnActionPerformed
        // TODO add your handling code here:
        transaksi = transaksiControl.searchTransaksi(selectedId);
        if(transaksi!=null){
            int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Periksa "+transaksi.getPasien().getNama()+"? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            switch(getAnswer){
                case 0:
                    namaPasienLabel.setText("Nama Pasien           "+transaksi.getPasien().getNama());
                    umurPasienLabel.setText("Umur Pasien           "+Integer.toString(transaksi.getPasien().getUmur())+" Tahun");
                    RawatDataInput.setLocationRelativeTo(null);
                    RawatDataInput.pack();
                    RawatDataInput.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    RawatDataInput.setVisible(true);
                    showKeranjangObat();
                    showKeranjangTindakan();
                    listener.buttonClicked(false);
                    break;
                case 1:
                    break;
            }   
        }else{
            errorDialog("Pilih pasien terlebih dahulu");
        }
        
    }//GEN-LAST:event_rawatBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
        try{
            inputKosongException();
            transaksi = new Transaksi(selectedId, transaksi.getTanggalTransaksi(), transaksi.getBiaya_klinik(), "Bayar", diagnosisInput.getText());
            transaksiControl.updateStatusDataTransaksi(transaksi);
            backToRawatView();
        }catch(InputKosongException e){
            errorDialog("Diagnosis tidak boleh kosong!");
        }
    }//GEN-LAST:event_okBtnActionPerformed

    private void addObatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObatBtnActionPerformed
        // TODO add your handling code here:
        int selectedIndexObat = obatDropdown.getSelectedIndex();
        try{
            if(selectedIndexObat>0 && Integer.parseInt(jumlahObatInput.getText()) > 0){
                Obat selectedObat = listObat.get(selectedIndexObat);
                Tindakan tindakan = new Tindakan(1, "", 0);
                DetailTransaksi dt = new DetailTransaksi(transaksi, selectedObat, tindakan, Integer.parseInt(jumlahObatInput.getText()));
                detailTransaksiControl.insertDetailTransaksi(dt);
                jumlahObatInput.setText("0");
                showKeranjangObat();
            }else if(Integer.parseInt(jumlahObatInput.getText()) < 1){
                errorDialog("Jumlah Obat harus lebih dari 0");
            }else {
                errorDialog("Pilih Obat yang benar");
            }
        }catch(NumberFormatException e){
            errorDialog("Jumlah Obat harus angka!");
        }
    }//GEN-LAST:event_addObatBtnActionPerformed

    private void addTindakanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTindakanBtnActionPerformed
        // TODO add your handling code here:
        int selectedIndexTindakan = tindakanDropdown.getSelectedIndex();
        if(selectedIndexTindakan>0){
            Tindakan selectedTindakan = listTindakan.get(selectedIndexTindakan);
            Obat obat = new Obat(1, "", 0, 0);
            DetailTransaksi dt = new DetailTransaksi(transaksi, obat, selectedTindakan, 0);
            detailTransaksiControl.insertDetailTransaksi(dt);
            showKeranjangTindakan();
        }else{
            errorDialog("Pilih Tindakan yang benar");
        }
    }//GEN-LAST:event_addTindakanBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        detailTransaksiControl.deleteAllDetailTransaksiFromIDTransaksi(selectedId);
        backToRawatView();
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame RawatDataInput;
    private javax.swing.JButton addObatBtn;
    private javax.swing.JButton addTindakanBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField diagnosisInput;
    private javax.swing.JLabel diagnosisLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jumlahObatInput;
    private javax.swing.JLabel namaPasienLabel;
    private javax.swing.JComboBox<Obat> obatDropdown;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton rawatBtn;
    private javax.swing.JButton riwayatBtn;
    private javax.swing.JTable tableKeranjangObat;
    private javax.swing.JTable tableKeranjangTindakan;
    private javax.swing.JTable tablePasien;
    private javax.swing.JComboBox<Tindakan> tindakanDropdown;
    private javax.swing.JLabel umurPasienLabel;
    // End of variables declaration//GEN-END:variables

    private void showPasien() {
        tablePasien.setModel(transaksiControl.showDataPasienPerDokter(loginData.getNama(), "Menunggu"));
    }

    private void showKeranjangObat() {
        tableKeranjangObat.setModel(detailTransaksiControl.showDataKeranjangObat("", selectedId));
    }

    private void showKeranjangTindakan() {
        tableKeranjangTindakan.setModel(detailTransaksiControl.showDataKeranjangTindakan("", selectedId));
    }

    private void setObatDropdown() {
        listObat = obatControl.showListObat("");
        for(int i=0; i<listObat.size();i++){
            obatDropdown.addItem(listObat.get(i));
        }
    }

    private void setTindakanDropdown() {
        listTindakan = tindakanControl.showTindakanBySearch("");
        for(int i=0; i<listTindakan.size();i++){
            tindakanDropdown.addItem(listTindakan.get(i));
        }
    }

    private void initRawatDataInput() {
        RawatDataInput.setLocationRelativeTo(null);
        RawatDataInput.pack();
        RawatDataInput.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    private void backToRawatView(){
        jumlahObatInput.setText("0");
        diagnosisInput.setText("");
        showPasien();
        listener.buttonClicked(true);
        RawatDataInput.setVisible(false);
    }
    
    private void errorDialog(String msg){
        JOptionPane.showConfirmDialog(RawatDataInput, msg,"Error",JOptionPane.DEFAULT_OPTION);
    }

    private void inputKosongException() throws InputKosongException{
        if(diagnosisInput.getText().isEmpty()){
            throw new InputKosongException();
        }
    }
}
