/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.dokter;

import control.CustomerControl;
import control.DetailTransaksiControl;
import control.ObatControl;
import control.TindakanControl;
import control.TransaksiControl;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;
import model.Customer;
import model.DetailTransaksi;
import model.Obat;
import model.Staf;
import model.Tindakan;
import model.Transaksi;

/**
 *
 * @author VICTUS
 */
public class TindakanView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PeriksaView
     */
    TransaksiControl transaksiControl = new TransaksiControl();
    DetailTransaksiControl detailTransaksiControl = new DetailTransaksiControl();
    ObatControl obatControl = new ObatControl();
    TindakanControl tindakanControl = new TindakanControl();
    CustomerControl customerControl = new CustomerControl();
    Staf loginData = null;
    Customer pasien = null;
    Transaksi temp = null;
    int selectedId = 0;
    
    List<Transaksi> listTransaksi;
    List<DetailTransaksi> listDetailTransaksi;
    List<Obat> listObat;
    List<Tindakan> listTindakan;
    
    public TindakanView(Staf loginData) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        transaksiControl = new TransaksiControl();
        detailTransaksiControl = new DetailTransaksiControl();
        obatControl = new ObatControl();
        tindakanControl = new TindakanControl();
        customerControl = new CustomerControl();
        this.loginData = loginData;
        showPasien();
        setObatToDropdown();
        setTindakanToDropdown();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PerawatanMenu = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaPasienLabel = new javax.swing.JLabel();
        umurPasienLabel = new javax.swing.JLabel();
        checkoutBtn = new javax.swing.JButton();
        obatDropdown = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jumlahObatInput = new javax.swing.JTextField();
        obatAddBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tindakanDropdown = new javax.swing.JComboBox<>();
        tindakanAddBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKeranjang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePasien = new javax.swing.JTable();
        checkBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PERAWATAN");

        namaPasienLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaPasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaPasienLabel.setText("Nama Pasien");

        umurPasienLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        umurPasienLabel.setForeground(new java.awt.Color(0, 0, 0));
        umurPasienLabel.setText("Umur Pasien");

        checkoutBtn.setText("Checkout");
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Obat");

        jumlahObatInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jumlahObatInput.setText("0");

        obatAddBtn.setText("Tambah");
        obatAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatAddBtnActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tindakan");

        tindakanAddBtn.setText("Tambah");
        tindakanAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tindakanAddBtnActionPerformed(evt);
            }
        });

        tableKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKeranjangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableKeranjang);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Keranjang");

        deleteBtn.setText("Hapus");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(umurPasienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaPasienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkoutBtn)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tindakanDropdown, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(obatDropdown, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahObatInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(obatAddBtn)
                                    .addComponent(tindakanAddBtn))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(namaPasienLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umurPasienLabel)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(deleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(obatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahObatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obatAddBtn))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tindakanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tindakanAddBtn))
                        .addGap(63, 63, 63)
                        .addComponent(checkoutBtn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PerawatanMenuLayout = new javax.swing.GroupLayout(PerawatanMenu.getContentPane());
        PerawatanMenu.getContentPane().setLayout(PerawatanMenuLayout);
        PerawatanMenuLayout.setHorizontalGroup(
            PerawatanMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PerawatanMenuLayout.setVerticalGroup(
            PerawatanMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablePasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePasien);

        checkBtn.setText("Tindak");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pilih Pasien Untuk Ditindaklanjuti");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(checkBtn)
                .addGap(46, 46, 46))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBtn))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePasienMouseClicked
        // TODO add your handling code here:
        int clickedRow = tablePasien.getSelectedRow();
        TableModel tableModel =tablePasien.getModel();
        pasien = customerControl.searchCustomerByID(Integer.parseInt(tableModel.getValueAt(clickedRow, 8).toString()));
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 6).toString());
        String keluhan = tableModel.getValueAt(clickedRow, 3).toString();
        String tanggal = tableModel.getValueAt(clickedRow, 7).toString();
        temp = new Transaksi(selectedId, tanggal, 50000, "DiObati", keluhan);
        if(evt.getClickCount()==2 && tablePasien.getSelectedRow()!=-1){
            checkBtn.setEnabled(true);
            checkBtn.doClick();
        }else if(tablePasien.getSelectedRow()!=-1){
            checkBtn.setEnabled(true);
        }
    }//GEN-LAST:event_tablePasienMouseClicked

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Periksa "+pasien.getNama()+"? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
            namaPasienLabel.setText("Nama\t: "+pasien.getNama());
            umurPasienLabel.setText("Umur\t: "+Integer.toString(pasien.getUmur())+" Tahun");
            temp = new Transaksi(temp.getId(), temp.getTanggalTransaksi(), temp.getBiaya_klinik(), temp.getStatus(), temp.getKeluhan());
            transaksiControl.updateStatusDataTransaksi(temp);
            showKeranjang();
            PerawatanMenu.setLocationRelativeTo(null);
            PerawatanMenu.pack();
            PerawatanMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            PerawatanMenu.setVisible(true);
            break;
            case 1:
            break;
        }
    }//GEN-LAST:event_checkBtnActionPerformed

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void obatAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatAddBtnActionPerformed
        // TODO add your handling code here:
        try{
            if(Integer.parseInt(jumlahObatInput.getText())>0){
                int selectedIndexObat = obatDropdown.getSelectedIndex();
                Obat selectedObat = listObat.get(selectedIndexObat);
                int selectedIndexTindakan = tindakanDropdown.getSelectedIndex();
                Tindakan selectedTindakan = listTindakan.get(selectedIndexTindakan);
                DetailTransaksi dt = new DetailTransaksi(temp, selectedObat, selectedTindakan , Integer.parseInt(jumlahObatInput.getText()));
                detailTransaksiControl.insertDetailTransaksi(dt);
                showKeranjang();
            }else{
                JOptionPane.showConfirmDialog(null, "Tidak Boleh Dibawah 0","Warning",JOptionPane.DEFAULT_OPTION);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_obatAddBtnActionPerformed

    private void tindakanAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tindakanAddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tindakanAddBtnActionPerformed

    private void tableKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKeranjangMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableKeranjangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame PerawatanMenu;
    private javax.swing.JButton checkBtn;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlahObatInput;
    private javax.swing.JLabel namaPasienLabel;
    private javax.swing.JButton obatAddBtn;
    private javax.swing.JComboBox<Obat> obatDropdown;
    private javax.swing.JTable tableKeranjang;
    private javax.swing.JTable tablePasien;
    private javax.swing.JButton tindakanAddBtn;
    private javax.swing.JComboBox<Tindakan> tindakanDropdown;
    private javax.swing.JLabel umurPasienLabel;
    // End of variables declaration//GEN-END:variables

    private void showPasien() {
        tablePasien.setModel(transaksiControl.showDataPasienPerDokter(loginData.getNama(), "Diperiksa"));
    }
    
    private void showKeranjang(){
        tableKeranjang.setModel(detailTransaksiControl.showDataDetailTransaksi("",selectedId));
    }

    private void setObatToDropdown() {
        listObat = obatControl.showListObat("");
        for(int i=0; i<listObat.size(); i++){
            obatDropdown.addItem(listObat.get(i));
        }
    }

    private void setTindakanToDropdown() {
        listTindakan = tindakanControl.showTindakanBySearch("");
        for(int i=0; i<listTindakan.size();i++){
            tindakanDropdown.addItem(listTindakan.get(i));
        }
    }
}
