/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prototype;

import control.DetailTransaksiControl;
import control.MutasiControl;
import control.TransaksiControl;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import model.Mutasi;
import model.Transaksi;
import utils.UtilTable;

/**
 *
 * @author VICTUS
 */
public class BayarPanel extends javax.swing.JPanel {

    /**
     * Creates new form BayarPanel
     */
    private MutasiControl mutasiControl;
    private TransaksiControl transaksiControl;
    private DetailTransaksiControl detailTransaksiControl;
    int selectedIDTransaksi=0;
    int selectedIDDetailTransaksi=0;
    String selectedPerawatan="";
    public BayarPanel() {
        initComponents();
        mutasiControl = new MutasiControl();
        transaksiControl = new TransaksiControl();
        detailTransaksiControl = new DetailTransaksiControl();
        
        detailsFrame.pack();
        detailsFrame.setLocationRelativeTo(this);
        
        
        setPayDelBtn(false);
        setTableBayar("");
        setTableObat();
        setTableTindakan();
        setListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailsFrame = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        detailsTxt = new javax.swing.JTextArea();
        okBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBayar = new javax.swing.JTable();
        searchTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableObat = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTindakan = new javax.swing.JTable();
        detailBtn = new javax.swing.JButton();
        payBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jumlahObatSpinner = new javax.swing.JSpinner();
        editBtn = new javax.swing.JButton();

        detailsTxt.setEditable(false);
        detailsTxt.setColumns(20);
        detailsTxt.setRows(5);
        jScrollPane4.setViewportView(detailsTxt);

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okBtn)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(okBtn)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout detailsFrameLayout = new javax.swing.GroupLayout(detailsFrame.getContentPane());
        detailsFrame.getContentPane().setLayout(detailsFrameLayout);
        detailsFrameLayout.setHorizontalGroup(
            detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        detailsFrameLayout.setVerticalGroup(
            detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tableBayar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBayarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBayar);

        tableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableObatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableObat);

        tableTindakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTindakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTindakanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableTindakan);

        detailBtn.setText("Detail");
        detailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBtnActionPerformed(evt);
            }
        });

        payBtn.setText("Pay");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Remove");
        delBtn.setEnabled(false);
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        jumlahObatSpinner.setEnabled(false);

        editBtn.setText("Edit");
        editBtn.setEnabled(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jumlahObatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(detailBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(payBtn)))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detailBtn)
                            .addComponent(payBtn))
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delBtn)
                            .addComponent(jumlahObatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editBtn))
                        .addGap(2, 2, 2)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableBayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBayarMouseClicked
        int clickedRow = tableBayar.getSelectedRow();
        TableModel tableModel = tableBayar.getModel();
        selectedIDTransaksi = Integer.parseInt(tableModel.getValueAt(clickedRow, 7).toString());
        setTableObat();
        setTableTindakan();
        setPayDelBtn(true);
    }//GEN-LAST:event_tableBayarMouseClicked

    private void tableObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableObatMouseClicked
        tableTindakan.clearSelection();
        int clickedRow = tableObat.getSelectedRow();
        TableModel tableModel = tableObat.getModel();
        selectedIDDetailTransaksi = Integer.parseInt(tableModel.getValueAt(clickedRow, 4).toString());
        selectedPerawatan = tableModel.getValueAt(clickedRow, 1).toString();
        jumlahObatSpinner.setValue(Integer.parseInt(tableModel.getValueAt(clickedRow, 2).toString()));
    }//GEN-LAST:event_tableObatMouseClicked

    private void tableTindakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTindakanMouseClicked
        tableObat.clearSelection();
        int clickedRow = tableTindakan.getSelectedRow();
        TableModel tableModel = tableTindakan.getModel();
        selectedIDDetailTransaksi = Integer.parseInt(tableModel.getValueAt(clickedRow, 3).toString());
        selectedPerawatan = tableModel.getValueAt(clickedRow, 1).toString();
    }//GEN-LAST:event_tableTindakanMouseClicked

    private void detailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBtnActionPerformed
        Transaksi transaksi = transaksiControl.searchTransaksi(selectedIDTransaksi);
        transaksi.setDetailTransaksiList(detailTransaksiControl.getListDetailTransaksiByTransaksiID("", transaksi.getId()));
        detailsTxt.setText(transaksi.showNota());
        detailsFrame.setVisible(true);
    }//GEN-LAST:event_detailBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        detailsFrame.setVisible(false);
    }//GEN-LAST:event_okBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin hapus "+selectedPerawatan+"?","Warning",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            detailTransaksiControl.deleteDetailTransaksi(selectedIDDetailTransaksi);
            setTableObat();
            setTableTindakan();
            setTableBayar("");
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        detailTransaksiControl.updateJumlahObat(selectedIDDetailTransaksi, (int)jumlahObatSpinner.getValue());
        setTableBayar("");
        setTableObat();
        editBtn.setEnabled(false);
    }//GEN-LAST:event_editBtnActionPerformed

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        Transaksi transaksi = transaksiControl.searchTransaksi(selectedIDTransaksi);
        transaksi.setDetailTransaksiList(detailTransaksiControl.getListDetailTransaksiByTransaksiID("",selectedIDTransaksi));
        int confirm = JOptionPane.showConfirmDialog(null, transaksi.getPasien().getNama()+ " sudah membayar? ","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            transaksi.setTanggalTransaksi(getCurrentDateAndTime());
            transaksi.setStatus("Selesai");
            transaksiControl.updateStatusDataTransaksi(transaksi);
            double saldo = mutasiControl.getSaldo() + transaksi.totalHarga();
            Mutasi m = new Mutasi(transaksi.getId(), 0, transaksi.totalHarga(), saldo, "Perawatan pasien "+transaksi.getPasien().getNama(), "Pemasukan", transaksi.getTanggalTransaksi());
            mutasiControl.insertDataMutasi(m);
            selectedIDTransaksi=0;
            setTableBayar("");
            setTableObat();
            setTableTindakan();
        }
    }//GEN-LAST:event_payBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delBtn;
    private javax.swing.JButton detailBtn;
    private javax.swing.JFrame detailsFrame;
    private javax.swing.JTextArea detailsTxt;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jumlahObatSpinner;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton payBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable tableBayar;
    private javax.swing.JTable tableObat;
    private javax.swing.JTable tableTindakan;
    // End of variables declaration//GEN-END:variables

    private void setTableBayar(String query) {
        tableBayar.setModel(transaksiControl.showDataPembayaranCustomer(query, "Bayar"));
    }

    private void setListener() {
        searchTxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setTableBayar(searchTxt.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setTableBayar(searchTxt.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setTableBayar(searchTxt.getText());
            }
        });
        
        tableObat.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    delBtn.setEnabled(tableObat.getSelectedRow() != -1 || tableTindakan.getSelectedRow() != -1);
                    jumlahObatSpinner.setEnabled(tableObat.getSelectedRow() != -1);
                    editBtn.setEnabled(tableObat.getSelectedRow() != -1);
                }
            }
        });
        tableTindakan.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    delBtn.setEnabled(tableObat.getSelectedRow() != -1 || tableTindakan.getSelectedRow() != -1);
                }
            }
        });
        jumlahObatSpinner.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int value = (int) jumlahObatSpinner.getValue();
                if (value < 1) {
                    jumlahObatSpinner.setValue(1);
                }
            }
        });
    }

    private void setPayDelBtn(boolean b) {
        payBtn.setEnabled(b);
        detailBtn.setEnabled(b);
    }

    private void setTableObat( ) {
        tableObat.setModel(detailTransaksiControl.showDataKeranjangObat("", selectedIDTransaksi));
        UtilTable.tableResizeColumnWidth(tableObat);
    }

    private void setTableTindakan( ) {
        tableTindakan.setModel(detailTransaksiControl.showDataKeranjangTindakan("", selectedIDTransaksi));
        UtilTable.tableResizeColumnWidth(tableTindakan);
    }

    private String getCurrentDateAndTime() {
        LocalDateTime currentDateTime = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String sqlDateandTime = currentDateTime.format(formatter);
        return sqlDateandTime;
    }
}
