/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prototype;

import com.formdev.flatlaf.FlatClientProperties;
import control.ObatControl;
import exception.InputKosongException;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;

/**
 *
 * @author VICTUS
 */
public class ObatPanel extends javax.swing.JPanel implements IPanelAdmin{

    private ObatControl obatControl;
    private int selectedID;
    public ObatPanel() {
        initComponents();
        obatControl = new ObatControl();
        namaObatTxt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nama obat");
        hargaObatTxt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Harga obat");
        searchTxt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Cari");
        try{
            inputKosongException();
        }catch(InputKosongException e){
            System.out.println(e.message());
        }finally{
            setTableObat("");
            setListener();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableObat = new javax.swing.JTable();
        searchTxt = new javax.swing.JTextField();
        namaObatTxt = new javax.swing.JTextField();
        hargaObatTxt = new javax.swing.JTextField();
        jumlahObatSpinner = new javax.swing.JSpinner();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();

        tableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableObatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableObat);

        namaObatTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaObatTxtActionPerformed(evt);
            }
        });

        addBtn.setText("Add");
        addBtn.setEnabled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.setEnabled(false);

        delBtn.setText("Delete");
        delBtn.setEnabled(false);
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editBtn)
                        .addGap(12, 12, 12)
                        .addComponent(delBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hargaObatTxt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jumlahObatSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearBtn))
                            .addComponent(namaObatTxt))
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delBtn)
                    .addComponent(addBtn)
                    .addComponent(editBtn)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaObatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaObatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahObatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearBtn)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delBtnActionPerformed

    private void namaObatTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaObatTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaObatTxtActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearAll();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void tableObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableObatMouseClicked
        int clickedRow = tableObat.getSelectedRow();
        TableModel tableModel = tableObat.getModel();
        selectedID = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        namaObatTxt.setText(tableModel.getValueAt(clickedRow, 1).toString());
        hargaObatTxt.setText(tableModel.getValueAt(clickedRow, 2).toString());
        jumlahObatSpinner.setValue(tableModel.getValueAt(clickedRow, 3));
    }//GEN-LAST:event_tableObatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField hargaObatTxt;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jumlahObatSpinner;
    private javax.swing.JTextField namaObatTxt;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable tableObat;
    // End of variables declaration//GEN-END:variables

    private void setTableObat(String query) {
        tableObat.setModel(obatControl.showDataObat(query));
    }

    private void setListener() {
        searchTxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setTableObat(searchTxt.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setTableObat(searchTxt.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setTableObat(searchTxt.getText());
            }
        });
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkFields();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkFields();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkFields();
            }

            
        };
        namaObatTxt.getDocument().addDocumentListener(docListener);
        hargaObatTxt.getDocument().addDocumentListener(docListener);
        
        jumlahObatSpinner.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int value = (int) jumlahObatSpinner.getValue();
                if(value<0){
                    jumlahObatSpinner.setValue(0);
                }
                checkFields();
            }
        });
        
        tableObat.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()){
                    checkFields();
                }
            }
        });
    }

    @Override
    public void refreshData() {
        setTableObat("");
        clearAll();
    }
    
    private void checkFields() {
        try{
            inputKosongException();
            int jumlah = (int) jumlahObatSpinner.getValue();
            Double harga = Double.parseDouble(hargaObatTxt.getText());
            addBtn.setEnabled(jumlah>0&&harga>0 && tableObat.getSelectedRow()==-1);
            editBtn.setEnabled(jumlah>0&&harga>0 && tableObat.getSelectedRow()!=-1);
            delBtn.setEnabled(tableObat.getSelectedRow()!=-1);
        }catch(InputKosongException ex){
            addBtn.setEnabled(false);
            editBtn.setEnabled(false);
        }catch(NumberFormatException nfe){
            addBtn.setEnabled(false);
            editBtn.setEnabled(false);
        }
        catch(Exception e){
            addBtn.setEnabled(false);
            editBtn.setEnabled(false);
        }
    }
    
    private void inputKosongException() throws InputKosongException{
        if(namaObatTxt.getText().isEmpty() || hargaObatTxt.getText().isEmpty()){
            throw new InputKosongException();
        }
    }

    private void clearAll() {
        searchTxt.setText("");
        namaObatTxt.setText("");
        hargaObatTxt.setText("");
        jumlahObatSpinner.setValue(0);
        addBtn.setEnabled(false);
        editBtn.setEnabled(false);
        delBtn.setEnabled(false);
        tableObat.clearSelection();
    }
}
