/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package KasirDashboard.CustomePalette;

import java.awt.Color;

/**
 *
 * @author dendy
 */
public class PanelServiceMenu extends javax.swing.JPanel {

    /**
     * Creates new form PanelServiceMenu
     */
    public PanelServiceMenu(Color c) {
        initComponents();
        setOpaque(false);
        setBackground(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel2 = new KasirDashboard.CustomePalette.roundedPanel();
        roundedPanel3 = new KasirDashboard.CustomePalette.roundedPanel();
        roundedPanel1 = new KasirDashboard.CustomePalette.roundedPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(3, 104, 218));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 139, -1, -1));

        roundedPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        add(roundedPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 259, -1, -1));

        roundedPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 379, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Services");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 480, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void roundedPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel2MouseClicked

    }//GEN-LAST:event_roundedPanel2MouseClicked

    private void roundedPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_roundedPanel3MouseClicked

    private void roundedPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedPanel1MouseClicked

    }//GEN-LAST:event_roundedPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private KasirDashboard.CustomePalette.roundedPanel roundedPanel1;
    private KasirDashboard.CustomePalette.roundedPanel roundedPanel2;
    private KasirDashboard.CustomePalette.roundedPanel roundedPanel3;
    // End of variables declaration//GEN-END:variables
}
