/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DokterDashboard;

import LoginNew.LoginView;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import control.DetailTransaksiControl;
import control.ObatControl;
import control.TindakanControl;
import control.TransaksiControl;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import model.DetailTransaksi;
import model.Obat;
import model.Staf;
import model.Tindakan;
import model.Transaksi;

/**
 *
 * @author dendy
 */
public class DokterView extends javax.swing.JFrame {

    private Object DokterDashboard;
    
    private TransaksiControl transaksiControl;
    private DetailTransaksiControl detailTransaksiControl;
    private ObatControl obatControl;
    private TindakanControl tindakanControl;
    private List<Obat> listObat;
    private List<Tindakan> listTindakan;
    private int SelectedID = 0;
    private int SelectedIDDetailTransaksi = 0;
    
    /**
     * Creates new form DokterView
     */
    private Staf loginData;
    
    public DokterView(Staf loginData) {
        this.loginData = loginData;
        initComponents();
        
        transaksiControl = new TransaksiControl();
        detailTransaksiControl = new DetailTransaksiControl();
        obatControl = new ObatControl();
        tindakanControl = new TindakanControl();
        diagnosisTxt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Diagnosis");
        namaPasienTxt.putClientProperty(FlatClientProperties.STYLE, ""
                +"borderWidth:0;"
                + "focusWidth:0");
        umurPasienTxt.putClientProperty(FlatClientProperties.STYLE, ""
                +"borderWidth:0;"
                + "focusWidth:0");
        setProfileDokter();
        setObatTindakanDropdown();
        setTablePasien();
        setTableObat();
        setTableTindakan();
        setListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameRawatInput = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        diagnosisTxt = new javax.swing.JTextField();
        obatDropdown = new javax.swing.JComboBox<>();
        jumlahObatSpinner = new javax.swing.JSpinner();
        addObatBtn = new javax.swing.JButton();
        tindakanDropdown = new javax.swing.JComboBox<>();
        addTindakanBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTindakan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableObat = new javax.swing.JTable();
        doneBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        namaPasienLabel = new javax.swing.JLabel();
        umurPasienLabel = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        namaPasienTxt = new javax.swing.JTextField();
        umurPasienTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        exitBtn3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        homeIcon = new javax.swing.JLabel();
        riwayatIcon = new javax.swing.JLabel();
        rawatIcon = new javax.swing.JLabel();
        namaLbl2 = new javax.swing.JLabel();
        riwayatLbl = new javax.swing.JLabel();
        namaLbl20 = new javax.swing.JLabel();
        homelbl = new javax.swing.JLabel();
        rawatLbl = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        logOutIcon = new javax.swing.JLabel();
        roundedPanelDokterPutih3 = new DokterDashboard.roundedPanelDokterPutih();
        panelDashboard = new DokterDashboard.roundedPanelDokterGradientTransparan();
        roundedPanelDokterPutih2 = new DokterDashboard.roundedPanelDokterPutih();
        roundedPanelDokterGradient3 = new DokterDashboard.roundedPanelDokterGradient();
        namaLbl19 = new javax.swing.JLabel();
        namaLbl6 = new javax.swing.JLabel();
        jumlahPasienSelesai = new javax.swing.JLabel();
        roundedPanelDokter1 = new DokterDashboard.roundedPanelDokter();
        namaDokterTxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        helloDokterTxt = new javax.swing.JLabel();
        notelpTxt = new javax.swing.JLabel();
        tanggalBergabungTxt = new javax.swing.JLabel();
        namaLbl14 = new javax.swing.JLabel();
        namaLbl15 = new javax.swing.JLabel();
        namaLbl16 = new javax.swing.JLabel();
        namaLbl17 = new javax.swing.JLabel();
        roundedPanelDokterPutih1 = new DokterDashboard.roundedPanelDokterPutih();
        roundedPanelDokterGradient1 = new DokterDashboard.roundedPanelDokterGradient();
        namaLbl18 = new javax.swing.JLabel();
        namaLbl3 = new javax.swing.JLabel();
        jumlahPasienTunggu = new javax.swing.JLabel();
        namaLbl4 = new javax.swing.JLabel();
        namaLbl5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePasienRawat = new DokterDashboard.TableDokterCustom();
        refreshBtn = new javax.swing.JButton();
        selectBtn = new javax.swing.JButton();

        frameRawatInput.setUndecorated(true);

        addObatBtn.setText("Add");
        addObatBtn.setEnabled(false);
        addObatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObatBtnActionPerformed(evt);
            }
        });

        addTindakanBtn.setText("Add");
        addTindakanBtn.setEnabled(false);
        addTindakanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTindakanBtnActionPerformed(evt);
            }
        });

        tableTindakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTindakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTindakanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableTindakan);

        tableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableObatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableObat);

        doneBtn.setText("Done");
        doneBtn.setEnabled(false);
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.setEnabled(false);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        namaPasienLabel.setText("Nama Pasien");

        umurPasienLabel.setText("Umur Pasien");

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        namaPasienTxt.setEditable(false);

        umurPasienTxt.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(doneBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(umurPasienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(namaPasienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(namaPasienTxt)
                                        .addComponent(umurPasienTxt)))
                                .addComponent(diagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(obatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jumlahObatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addObatBtn))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tindakanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addTindakanBtn)))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPasienLabel)
                    .addComponent(namaPasienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurPasienLabel)
                    .addComponent(umurPasienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(diagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahObatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addObatBtn)
                    .addComponent(tindakanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTindakanBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBtn)
                    .addComponent(doneBtn)
                    .addComponent(cancelBtn))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout frameRawatInputLayout = new javax.swing.GroupLayout(frameRawatInput.getContentPane());
        frameRawatInput.getContentPane().setLayout(frameRawatInputLayout);
        frameRawatInputLayout.setHorizontalGroup(
            frameRawatInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameRawatInputLayout.setVerticalGroup(
            frameRawatInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 246, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 91, 231));

        exitBtn3.setBackground(new java.awt.Color(255, 102, 102));
        exitBtn3.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn3.setText("x");
        exitBtn3.setBorder(null);
        exitBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(1024, Short.MAX_VALUE)
                .addComponent(exitBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        jPanel6.setBackground(new java.awt.Color(0, 66, 175));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/home.png"))); // NOI18N
        jPanel6.add(homeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 50));

        riwayatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/history.png"))); // NOI18N
        jPanel6.add(riwayatIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 50));

        rawatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/medical-symbol.png"))); // NOI18N
        jPanel6.add(rawatIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 50));

        namaLbl2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        namaLbl2.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl2.setText("ATMA UNIVERSAL");
        jPanel6.add(namaLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, 25));

        riwayatLbl.setBackground(new java.awt.Color(0, 102, 51));
        riwayatLbl.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        riwayatLbl.setForeground(new java.awt.Color(255, 255, 255));
        riwayatLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        riwayatLbl.setText("          Riwayat Periksa");
        riwayatLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatLblMouseExited(evt);
            }
        });
        jPanel6.add(riwayatLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 50));

        namaLbl20.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        namaLbl20.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl20.setText("CLINIC");
        jPanel6.add(namaLbl20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 25));

        homelbl.setBackground(new java.awt.Color(0, 102, 51));
        homelbl.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        homelbl.setForeground(new java.awt.Color(255, 255, 255));
        homelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homelbl.setText("          Home");
        homelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homelblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homelblMouseExited(evt);
            }
        });
        jPanel6.add(homelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 50));

        rawatLbl.setBackground(new java.awt.Color(0, 102, 51));
        rawatLbl.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        rawatLbl.setForeground(new java.awt.Color(255, 255, 255));
        rawatLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rawatLbl.setText("          Rawat Pasien");
        rawatLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rawatLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rawatLblMouseExited(evt);
            }
        });
        jPanel6.add(rawatLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 50));

        LogOut.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogOut.setText("             Log out");
        LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutMouseExited(evt);
            }
        });
        jPanel6.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 240, 50));

        logOutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/logout.png"))); // NOI18N
        jPanel6.add(logOutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, 30));

        roundedPanelDokterPutih3.setBackground(new java.awt.Color(245, 246, 250));

        javax.swing.GroupLayout roundedPanelDokterPutih3Layout = new javax.swing.GroupLayout(roundedPanelDokterPutih3);
        roundedPanelDokterPutih3.setLayout(roundedPanelDokterPutih3Layout);
        roundedPanelDokterPutih3Layout.setHorizontalGroup(
            roundedPanelDokterPutih3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        roundedPanelDokterPutih3Layout.setVerticalGroup(
            roundedPanelDokterPutih3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel6.add(roundedPanelDokterPutih3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 250, 60));

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 250, 639));

        namaLbl19.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        namaLbl19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/healthy-living.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanelDokterGradient3Layout = new javax.swing.GroupLayout(roundedPanelDokterGradient3);
        roundedPanelDokterGradient3.setLayout(roundedPanelDokterGradient3Layout);
        roundedPanelDokterGradient3Layout.setHorizontalGroup(
            roundedPanelDokterGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(namaLbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        roundedPanelDokterGradient3Layout.setVerticalGroup(
            roundedPanelDokterGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLbl19, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        namaLbl6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        namaLbl6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl6.setText("Selesai Perawatan");

        jumlahPasienSelesai.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jumlahPasienSelesai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienSelesai.setText("10 Pasien");

        javax.swing.GroupLayout roundedPanelDokterPutih2Layout = new javax.swing.GroupLayout(roundedPanelDokterPutih2);
        roundedPanelDokterPutih2.setLayout(roundedPanelDokterPutih2Layout);
        roundedPanelDokterPutih2Layout.setHorizontalGroup(
            roundedPanelDokterPutih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelDokterPutih2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(roundedPanelDokterGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanelDokterPutih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLbl6)
                    .addComponent(jumlahPasienSelesai))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        roundedPanelDokterPutih2Layout.setVerticalGroup(
            roundedPanelDokterPutih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterPutih2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(roundedPanelDokterPutih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundedPanelDokterPutih2Layout.createSequentialGroup()
                        .addComponent(jumlahPasienSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roundedPanelDokterGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel1.add(roundedPanelDokterPutih2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 300, -1));

        roundedPanelDokter1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaDokterTxt.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        namaDokterTxt.setForeground(new java.awt.Color(255, 255, 255));
        namaDokterTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaDokterTxt.setText("John Cena");
        roundedPanelDokter1.add(namaDokterTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/profile putih.png"))); // NOI18N
        roundedPanelDokter1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 136));

        helloDokterTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        helloDokterTxt.setForeground(new java.awt.Color(255, 255, 255));
        helloDokterTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helloDokterTxt.setText("Hallo Dokter");
        roundedPanelDokter1.add(helloDokterTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 25));

        notelpTxt.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        notelpTxt.setForeground(new java.awt.Color(255, 255, 255));
        notelpTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        notelpTxt.setText("089 642 200 012");
        roundedPanelDokter1.add(notelpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 25));

        tanggalBergabungTxt.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        tanggalBergabungTxt.setForeground(new java.awt.Color(255, 255, 255));
        tanggalBergabungTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggalBergabungTxt.setText("23 Juli 2020");
        roundedPanelDokter1.add(tanggalBergabungTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, 25));

        namaLbl14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        namaLbl14.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl14.setText("No Handphone");
        roundedPanelDokter1.add(namaLbl14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 92, 25));

        namaLbl15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        namaLbl15.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl15.setText("Tanggal Bergabung");
        roundedPanelDokter1.add(namaLbl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 130, 25));

        namaLbl16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        namaLbl16.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl16.setText("Nama Dokter");
        roundedPanelDokter1.add(namaLbl16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 92, 25));

        namaLbl17.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        namaLbl17.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl17.setText("Profile Dokter");
        roundedPanelDokter1.add(namaLbl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 25));

        jPanel1.add(roundedPanelDokter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 380, 250));

        namaLbl18.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        namaLbl18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/timer.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanelDokterGradient1Layout = new javax.swing.GroupLayout(roundedPanelDokterGradient1);
        roundedPanelDokterGradient1.setLayout(roundedPanelDokterGradient1Layout);
        roundedPanelDokterGradient1Layout.setHorizontalGroup(
            roundedPanelDokterGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(namaLbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        roundedPanelDokterGradient1Layout.setVerticalGroup(
            roundedPanelDokterGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLbl18, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        namaLbl3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        namaLbl3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl3.setText("Menunggu Perawatan");

        jumlahPasienTunggu.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jumlahPasienTunggu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienTunggu.setText("5 Pasien");

        javax.swing.GroupLayout roundedPanelDokterPutih1Layout = new javax.swing.GroupLayout(roundedPanelDokterPutih1);
        roundedPanelDokterPutih1.setLayout(roundedPanelDokterPutih1Layout);
        roundedPanelDokterPutih1Layout.setHorizontalGroup(
            roundedPanelDokterPutih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelDokterPutih1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(roundedPanelDokterGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanelDokterPutih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLbl3)
                    .addComponent(jumlahPasienTunggu))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        roundedPanelDokterPutih1Layout.setVerticalGroup(
            roundedPanelDokterPutih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelDokterPutih1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(roundedPanelDokterPutih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundedPanelDokterGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanelDokterPutih1Layout.createSequentialGroup()
                        .addComponent(jumlahPasienTunggu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(roundedPanelDokterPutih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 300, 100));

        namaLbl4.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        namaLbl4.setForeground(new java.awt.Color(3, 104, 218));
        namaLbl4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl4.setText("Dashboard> ");
        jPanel1.add(namaLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, 25));

        namaLbl5.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        namaLbl5.setForeground(new java.awt.Color(3, 104, 218));
        namaLbl5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl5.setText("Home");
        jPanel1.add(namaLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 92, 25));

        tablePasienRawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePasienRawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePasienRawatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePasienRawat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 710, 290));

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        jPanel1.add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, -1, -1));

        selectBtn.setText("Select");
        selectBtn.setEnabled(false);
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });
        jPanel1.add(selectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtn3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitBtn3ActionPerformed

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        // TODO add your handling code here:
        

//        int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Yakin ingin Log Out ? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);
//        switch(getAnswer){
//            case 0:
//            LoginView mp = new LoginView();
//            mp.setVisible(true);
//            this.setVisible(false);
//            break;
//
//            case 1:
////            LogoutPanel.setVisible(false);
//            LogOut.setForeground(defaultColor);
//            Icon icon5 = new ImageIcon(getClass().getResource("/Aset/logout.png"));
//            logOutIcon.setIcon(icon5);
//            HomeLblMouseClicked(evt);
//            break;
//        }

    }//GEN-LAST:event_LogOutMouseClicked

    private void LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseEntered
        // TODO add your handling code here:
//        LogoutPanel.setVisible(true);
//        LogOut.setForeground(selectedColor);
//        Icon icon = new ImageIcon(getClass().getResource("/Aset/logout (1).png"));
//        logOutIcon.setIcon(icon);
    }//GEN-LAST:event_LogOutMouseEntered

    private void LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseExited
        // TODO add your handling code here:
//        if(!selectLogout){
//            LogoutPanel.setVisible(false);
//            LogOut.setForeground(defaultColor);
//            Icon icon = new ImageIcon(getClass().getResource("/Aset/logout.png"));
//            logOutIcon.setIcon(icon);
//        }

    }//GEN-LAST:event_LogOutMouseExited

    private void homelblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelblMouseEntered
        // TODO add your handling code here:
        panelDashboard.setVisible(true);
        panelDashboard.setLocation(panelDashboard.getX(), 120);
        
    }//GEN-LAST:event_homelblMouseEntered

    private void rawatLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawatLblMouseEntered
        // TODO add your handling code here:
        panelDashboard.setVisible(true);
        panelDashboard.setLocation(panelDashboard.getX(), 180);
    }//GEN-LAST:event_rawatLblMouseEntered

    private void riwayatLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatLblMouseEntered
        // TODO add your handling code here:
        panelDashboard.setVisible(true);
        panelDashboard.setLocation(panelDashboard.getX(), 240);
    }//GEN-LAST:event_riwayatLblMouseEntered

    private void rawatLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawatLblMouseExited
        // TODO add your handling code here:
//        panelDashboard.setVisible(false);
    }//GEN-LAST:event_rawatLblMouseExited

    private void riwayatLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatLblMouseExited
        // TODO add your handling code here:
//        panelDashboard.setVisible(false);
    }//GEN-LAST:event_riwayatLblMouseExited

    private void homelblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelblMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_homelblMouseExited

    private void addObatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObatBtnActionPerformed
        Obat obat = (Obat) obatDropdown.getSelectedItem();
        Tindakan tindakan = (Tindakan) tindakanDropdown.getItemAt(0);
        int jumlahObat = (int) jumlahObatSpinner.getValue();
        DetailTransaksi dt = new DetailTransaksi(SelectedID, obat, tindakan, jumlahObat);
        int idDetailTransaksi = detailTransaksiControl.checkDetailSama(SelectedID, obat.getId(), "obat");
        if(idDetailTransaksi==0){//cek jika belum ada detail transaksi dengan obat sama
            detailTransaksiControl.insertDetailTransaksi(dt);
        }else{
            dt.setId_detail_transaksi(idDetailTransaksi);
            detailTransaksiControl.updateDetailTransaksi(dt);
        }
        setTableObat();
        doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty()&&!isTableObatTindakanEmpty());
    }//GEN-LAST:event_addObatBtnActionPerformed

    private void addTindakanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTindakanBtnActionPerformed
        Obat obat = (Obat) obatDropdown.getItemAt(0);
        Tindakan tindakan = (Tindakan) tindakanDropdown.getSelectedItem();
        DetailTransaksi dt = new DetailTransaksi(SelectedID, obat, tindakan, 0);
        int idDetailTransaksi = detailTransaksiControl.checkDetailSama(SelectedID, tindakan.getId(), "tindakan");
        if(idDetailTransaksi==0){//cek jika belum ada detail transaksi dengan obat sama
            detailTransaksiControl.insertDetailTransaksi(dt);
        }else{
            dt.setId_detail_transaksi(idDetailTransaksi);
            detailTransaksiControl.updateDetailTransaksi(dt);
        }
        setTableTindakan();
        doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty()&&!isTableObatTindakanEmpty());
    }//GEN-LAST:event_addTindakanBtnActionPerformed

    private void tableTindakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTindakanMouseClicked
        tableObat.clearSelection();
        SelectedIDDetailTransaksi = Integer.parseInt(tableTindakan.getModel().getValueAt(tableTindakan.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tableTindakanMouseClicked

    private void tableObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableObatMouseClicked
        tableTindakan.clearSelection();
        SelectedIDDetailTransaksi = Integer.parseInt(tableObat.getModel().getValueAt(tableObat.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tableObatMouseClicked

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Selesai merawat "+tablePasienRawat.getModel().getValueAt(tablePasienRawat.getSelectedRow(), 1).toString(),"Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            Transaksi transaksi = transaksiControl.searchTransaksi(SelectedID);
            transaksi.setStatus("Bayar");
            transaksi.setDiagnosis(diagnosisTxt.getText());
            transaksi.setTanggalTransaksi(transaksi.dateTimeNowinString());
            transaksiControl.updateStatusDataTransaksi(transaksi);
            setTablePasien();
            SelectedID=0;
            setTableObat();
            setTableTindakan();
            tablePasienRawat.setEnabled(true);
            doneBtn.setEnabled(false);
            frameRawatInput.setVisible(false);
        }
    }//GEN-LAST:event_doneBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        detailTransaksiControl.deleteDetailTransaksi(SelectedIDDetailTransaksi);
        setTableObat();
        setTableTindakan();
        doneBtn.setEnabled(tableObat.getRowCount()!=0||tableTindakan.getRowCount()!=0);
        SelectedIDDetailTransaksi=0;
    }//GEN-LAST:event_removeBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        SelectedID = Integer.parseInt(tablePasienRawat.getModel().getValueAt(tablePasienRawat.getSelectedRow(), 6).toString());
        
        Transaksi transaksi = transaksiControl.searchTransaksi(SelectedID);
        namaPasienTxt.setText(transaksi.getPasien().getNama());
        umurPasienTxt.setText(transaksi.getPasien().getUmur()+" Tahun");
        tablePasienRawat.setEnabled(false);
        setTableObat();
        setTableTindakan();
        
        diagnosisTxt.putClientProperty("JComponent.outline", "error");
        frameRawatInput.pack();
        frameRawatInput.setLocationRelativeTo(null);
        frameRawatInput.setVisible(true);
    }//GEN-LAST:event_selectBtnActionPerformed

    private void tablePasienRawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePasienRawatMouseClicked
        
    }//GEN-LAST:event_tablePasienRawatMouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        frameRawatInput.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        setTablePasien();
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        
        FlatMacLightLaf.setup();
        UIManager.put( "Button.arc", 999);
        UIManager.put( "Component.arc", 999 );
        UIManager.put( "TextComponent.arc", 999 );
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Staf loginData = new Staf(9, "Dendy", "089643938007", "2023-05-31", "Dokter", "dendy", "dendy");
                new DokterView(loginData).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogOut;
    private javax.swing.JButton addObatBtn;
    private javax.swing.JButton addTindakanBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField diagnosisTxt;
    private javax.swing.JButton doneBtn;
    private javax.swing.JButton exitBtn3;
    private javax.swing.JFrame frameRawatInput;
    private javax.swing.JLabel helloDokterTxt;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JLabel homelbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jumlahObatSpinner;
    private javax.swing.JLabel jumlahPasienSelesai;
    private javax.swing.JLabel jumlahPasienTunggu;
    private javax.swing.JLabel logOutIcon;
    private javax.swing.JLabel namaDokterTxt;
    private javax.swing.JLabel namaLbl14;
    private javax.swing.JLabel namaLbl15;
    private javax.swing.JLabel namaLbl16;
    private javax.swing.JLabel namaLbl17;
    private javax.swing.JLabel namaLbl18;
    private javax.swing.JLabel namaLbl19;
    private javax.swing.JLabel namaLbl2;
    private javax.swing.JLabel namaLbl20;
    private javax.swing.JLabel namaLbl3;
    private javax.swing.JLabel namaLbl4;
    private javax.swing.JLabel namaLbl5;
    private javax.swing.JLabel namaLbl6;
    private javax.swing.JLabel namaPasienLabel;
    private javax.swing.JTextField namaPasienTxt;
    private javax.swing.JLabel notelpTxt;
    private javax.swing.JComboBox<Obat> obatDropdown;
    private DokterDashboard.roundedPanelDokterGradientTransparan panelDashboard;
    private javax.swing.JLabel rawatIcon;
    private javax.swing.JLabel rawatLbl;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JLabel riwayatIcon;
    private javax.swing.JLabel riwayatLbl;
    private DokterDashboard.roundedPanelDokter roundedPanelDokter1;
    private DokterDashboard.roundedPanelDokterGradient roundedPanelDokterGradient1;
    private DokterDashboard.roundedPanelDokterGradient roundedPanelDokterGradient3;
    private DokterDashboard.roundedPanelDokterPutih roundedPanelDokterPutih1;
    private DokterDashboard.roundedPanelDokterPutih roundedPanelDokterPutih2;
    private DokterDashboard.roundedPanelDokterPutih roundedPanelDokterPutih3;
    private javax.swing.JButton selectBtn;
    private javax.swing.JTable tableObat;
    private DokterDashboard.TableDokterCustom tablePasienRawat;
    private javax.swing.JTable tableTindakan;
    private javax.swing.JLabel tanggalBergabungTxt;
    private javax.swing.JComboBox<Tindakan> tindakanDropdown;
    private javax.swing.JLabel umurPasienLabel;
    private javax.swing.JTextField umurPasienTxt;
    // End of variables declaration//GEN-END:variables


    private void setProfileDokter(){
        namaDokterTxt.setText(loginData.getNama());
        helloDokterTxt.setText("Dokter "+loginData.getNama());
        notelpTxt.setText(loginData.getNo_telepon());
        tanggalBergabungTxt.setText(loginData.getTanggal_bergabung());
        
    }
    private void setTablePasien() {
        tablePasienRawat.setModel(transaksiControl.showDataPasienPerDokter(loginData.getId(), "Menunggu"));
        jumlahPasienTunggu.setText(tablePasienRawat.getRowCount()+" Pasien");
        jumlahPasienSelesai.setText(transaksiControl.showDataPasienPerDokter(loginData.getId(), "Selesai").getRowCount()+" Pasien");
    }
    private void setObatTindakanDropdown() {
        listObat = obatControl.showListObat("");
        obatDropdown.removeAllItems();
        for(Obat o:listObat){
            obatDropdown.addItem(o);
        }
        listTindakan = tindakanControl.showListTindakan("");
        tindakanDropdown.removeAllItems();
        for(Tindakan t : listTindakan){
            tindakanDropdown.addItem(t);
        }
    }
    private void setTableObat(){
        tableObat.setModel(detailTransaksiControl.showDataKeranjangObat("", SelectedID));
        
    }
    private void setTableTindakan(){
        tableTindakan.setModel(detailTransaksiControl.showDataKeranjangTindakan("", SelectedID));
        
    }
    private void setListener() {
        tablePasienRawat.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    boolean isRowSelected = tablePasienRawat.getSelectedRow() != -1;
                    boolean isColumnSelected = tablePasienRawat.getSelectedColumn() != -1;

                    selectBtn.setEnabled(isRowSelected || isColumnSelected);
                    cancelBtn.setEnabled(isRowSelected || isColumnSelected);
                }
            }
        });
        
        tableObat.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    isTableObatTindakanSelected();
                }
            }
        });
        
        tableTindakan.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    isTableObatTindakanSelected();
                }
            }
        });
        
        jumlahObatSpinner.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int value = (int) jumlahObatSpinner.getValue();
                if(value<0){
                    jumlahObatSpinner.setValue(0);
                }else{
                    isObatSelected();
                }
            }
        });
        
        obatDropdown.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                isObatSelected();
            }
        });
        
        tindakanDropdown.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addTindakanBtn.setEnabled(tindakanDropdown.getSelectedIndex()!=0);
            }
        });
        
        diagnosisTxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                if(!diagnosisTxt.getText().isEmpty()){
                    diagnosisTxt.putClientProperty("JComponent.outline", "#FF000");
                }else{
                    diagnosisTxt.putClientProperty("JComponent.outline", "error");
                }
                doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty()&&!isTableObatTindakanEmpty());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if(!diagnosisTxt.getText().isEmpty()){
                    diagnosisTxt.putClientProperty("JComponent.outline", "#FF000");
                }else{
                    diagnosisTxt.putClientProperty("JComponent.outline", "error");
                }
                doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty()&&!isTableObatTindakanEmpty());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                if(!diagnosisTxt.getText().isEmpty()){
                    diagnosisTxt.putClientProperty("JComponent.outline", "#FF000");
                    doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty());
                }else{
                    diagnosisTxt.putClientProperty("JComponent.outline", "error");
                }
                doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty()&&!isTableObatTindakanEmpty());
            }
        });
        
    }
    private boolean isTableObatTindakanEmpty(){
        return (tableObat.getRowCount()==0&&tableTindakan.getRowCount()==0);
    }
    private void isTableObatTindakanSelected(){
        removeBtn.setEnabled(tableObat.getSelectedRow()!=-1 || tableTindakan.getSelectedRow()!=-1);
    }
    private void isObatSelected(){
        addObatBtn.setEnabled((int)jumlahObatSpinner.getValue()>0 && obatDropdown.getSelectedIndex()!=0);
    }
    
}
