/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DokterDashboard;


import LoginNew.LoginView;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import control.DetailTransaksiControl;
import control.ObatControl;
import control.TindakanControl;
import control.TransaksiControl;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import model.DetailTransaksi;
import model.Obat;
import model.Staf;
import model.Tindakan;
import model.Transaksi;

/**
 *
 * @author dendy
 */
public class DokterView extends javax.swing.JFrame {

    private Object DokterDashboard;
    
    private TransaksiControl transaksiControl;
    private DetailTransaksiControl detailTransaksiControl;
    private ObatControl obatControl;
    private TindakanControl tindakanControl;
    private List<Obat> listObat;
    private List<Tindakan> listTindakan;
    private int SelectedID = 0;
    private int SelectedIDDetailTransaksi = 0;
    
    /**
     * Creates new form DokterView
     */
    private Staf loginData;
//    boolean homeSelected=true,rawatSelected=false, riwayatSelected=false;
    Color selectedColor = new Color(0,66,175);
    Color defaultColor = new Color(255,255,255);
    public DokterView(Staf loginData) {
        this.loginData = loginData;
        initComponents();
        tableRawatPasien.setDataLogin(loginData);
        tableRawatPasien.setTableRawatPasien();
        riwayatTransaksiDokterForm1.setDataLogin(loginData);
        riwayatTransaksiDokterForm1.setDataRiwayat();
        riwayatTransaksiDokterForm1.setProfileDokter();
       
        setPanelSelected(true, false, false);
        transaksiControl = new TransaksiControl();
        detailTransaksiControl = new DetailTransaksiControl();
        obatControl = new ObatControl();
        tindakanControl = new TindakanControl();
        setTablePasien();
        setProfileDokter();
    }
    
    
    
    public void checkHomePanelSelected(boolean home){
        if(home){
            homelbl.setForeground(selectedColor);
            Icon icon = new ImageIcon(getClass().getResource("/Aset/home(2).png"));
            homeIcon.setIcon(icon);
            selectedHomePanel.setLocation(selectedHomePanel.getX(), 120);
            homePanel.setVisible(true);
            rawatPanel.setVisible(false);
            riwayatPanel.setVisible(false);
        }else{
           homelbl.setForeground(defaultColor);
           Icon icon = new ImageIcon(getClass().getResource("/Aset/home.png"));
           homeIcon.setIcon(icon);
        }
    }
    
    public void checkRawatPanelSelected(boolean rawat){
        if(rawat){
            rawatLbl.setForeground(selectedColor);
            Icon icon = new ImageIcon(getClass().getResource("/Aset/medical-symbol(1).png"));
            rawatIcon.setIcon(icon);
            homePanel.setVisible(false);
            rawatPanel.setVisible(true);
            riwayatPanel.setVisible(false);
        }else{
           rawatLbl.setForeground(defaultColor);
           Icon icon = new ImageIcon(getClass().getResource("/Aset/medical-symbol.png"));
           rawatIcon.setIcon(icon);
        }
    }
    
    public void checkRiwayatPanelSelected(boolean riwayat){
        if(riwayat){
            riwayatLbl.setForeground(selectedColor);
            Icon icon = new ImageIcon(getClass().getResource("/Aset/history(1).png"));
            riwayatIcon.setIcon(icon);
            homePanel.setVisible(false);
            rawatPanel.setVisible(false);
            riwayatPanel.setVisible(true);
        }else{
           riwayatLbl.setForeground(defaultColor);
           Icon icon = new ImageIcon(getClass().getResource("/Aset/history.png"));
           riwayatIcon.setIcon(icon);
        }
    }
    
    
    public void setPanelSelected(boolean home, boolean rawat, boolean riwayat){
        checkHomePanelSelected(home);
        checkRawatPanelSelected(rawat);
        checkRiwayatPanelSelected(riwayat);
        selectedHomePanel.setVisible(home);
        selectedRawatPanel.setVisible(rawat);
        selectedRiwayatPanel.setVisible(riwayat);
        selectedLogoutPanel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        exitBtn3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        homeIcon = new javax.swing.JLabel();
        riwayatIcon = new javax.swing.JLabel();
        rawatIcon = new javax.swing.JLabel();
        namaLbl2 = new javax.swing.JLabel();
        riwayatLbl = new javax.swing.JLabel();
        namaLbl20 = new javax.swing.JLabel();
        homelbl = new javax.swing.JLabel();
        rawatLbl = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        logOutIcon = new javax.swing.JLabel();
        selectedLogoutPanel = new DokterDashboard.roundedPanelDokterPutih();
        selectedRawatPanel = new DokterDashboard.roundedPanelDokterPutih();
        selectedRiwayatPanel = new DokterDashboard.roundedPanelDokterPutih();
        selectedHomePanel = new DokterDashboard.roundedPanelDokterPutih();
        panelDashboard = new DokterDashboard.roundedPanelDokterGradientTransparan();
        riwayatPanel = new javax.swing.JPanel();
        riwayatTransaksiDokterForm1 = new DokterDashboard.RiwayatTransaksiDokterForm();
        rawatPanel = new javax.swing.JPanel();
        tableRawatPasien = new DokterDashboard.RawatPasienForm();
        homePanel = new javax.swing.JPanel();
        roundedPanelDokterPutih2 = new DokterDashboard.roundedPanelDokterPutih();
        roundedPanelDokterGradient3 = new DokterDashboard.roundedPanelDokterGradient();
        namaLbl19 = new javax.swing.JLabel();
        namaLbl6 = new javax.swing.JLabel();
        jumlahPasienSelesai = new javax.swing.JLabel();
        roundedPanelDokter1 = new DokterDashboard.roundedPanelDokter();
        namaDokterTxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        helloDokterTxt = new javax.swing.JLabel();
        notelpTxt = new javax.swing.JLabel();
        tanggalBergabungTxt = new javax.swing.JLabel();
        namaLbl14 = new javax.swing.JLabel();
        namaLbl15 = new javax.swing.JLabel();
        namaLbl16 = new javax.swing.JLabel();
        namaLbl17 = new javax.swing.JLabel();
        roundedPanelDokterPutih1 = new DokterDashboard.roundedPanelDokterPutih();
        roundedPanelDokterGradient1 = new DokterDashboard.roundedPanelDokterGradient();
        namaLbl18 = new javax.swing.JLabel();
        namaLbl3 = new javax.swing.JLabel();
        jumlahPasienTunggu = new javax.swing.JLabel();
        namaLbl4 = new javax.swing.JLabel();
        namaLbl5 = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePasienRawat = new DokterDashboard.TableDokterCustomStatus();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 246, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 91, 231));

        exitBtn3.setBackground(new java.awt.Color(255, 102, 102));
        exitBtn3.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn3.setText("x");
        exitBtn3.setBorder(null);
        exitBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(1024, Short.MAX_VALUE)
                .addComponent(exitBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        jPanel6.setBackground(new java.awt.Color(0, 66, 175));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/home.png"))); // NOI18N
        jPanel6.add(homeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 50));

        riwayatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/history.png"))); // NOI18N
        jPanel6.add(riwayatIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 50));

        rawatIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/medical-symbol.png"))); // NOI18N
        jPanel6.add(rawatIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 50));

        namaLbl2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        namaLbl2.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl2.setText("ATMA UNIVERSAL");
        jPanel6.add(namaLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, 25));

        riwayatLbl.setBackground(new java.awt.Color(0, 102, 51));
        riwayatLbl.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        riwayatLbl.setForeground(new java.awt.Color(255, 255, 255));
        riwayatLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        riwayatLbl.setText("          Riwayat Periksa");
        riwayatLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                riwayatLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                riwayatLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                riwayatLblMouseExited(evt);
            }
        });
        jPanel6.add(riwayatLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 50));

        namaLbl20.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        namaLbl20.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl20.setText("CLINIC");
        jPanel6.add(namaLbl20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 25));

        homelbl.setBackground(new java.awt.Color(0, 102, 51));
        homelbl.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        homelbl.setForeground(new java.awt.Color(255, 255, 255));
        homelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homelbl.setText("          Home");
        homelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homelblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homelblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homelblMouseExited(evt);
            }
        });
        jPanel6.add(homelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 50));

        rawatLbl.setBackground(new java.awt.Color(0, 102, 51));
        rawatLbl.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        rawatLbl.setForeground(new java.awt.Color(255, 255, 255));
        rawatLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rawatLbl.setText("          Rawat Pasien");
        rawatLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rawatLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rawatLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rawatLblMouseExited(evt);
            }
        });
        jPanel6.add(rawatLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 50));

        LogOut.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogOut.setText("             Log out");
        LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutMouseExited(evt);
            }
        });
        jPanel6.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 240, 50));

        logOutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/logout.png"))); // NOI18N
        jPanel6.add(logOutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, 30));

        selectedLogoutPanel.setBackground(new java.awt.Color(245, 246, 250));

        javax.swing.GroupLayout selectedLogoutPanelLayout = new javax.swing.GroupLayout(selectedLogoutPanel);
        selectedLogoutPanel.setLayout(selectedLogoutPanelLayout);
        selectedLogoutPanelLayout.setHorizontalGroup(
            selectedLogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        selectedLogoutPanelLayout.setVerticalGroup(
            selectedLogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(selectedLogoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 250, 50));

        selectedRawatPanel.setBackground(new java.awt.Color(245, 246, 250));

        javax.swing.GroupLayout selectedRawatPanelLayout = new javax.swing.GroupLayout(selectedRawatPanel);
        selectedRawatPanel.setLayout(selectedRawatPanelLayout);
        selectedRawatPanelLayout.setHorizontalGroup(
            selectedRawatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        selectedRawatPanelLayout.setVerticalGroup(
            selectedRawatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(selectedRawatPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 250, 50));

        selectedRiwayatPanel.setBackground(new java.awt.Color(245, 246, 250));

        javax.swing.GroupLayout selectedRiwayatPanelLayout = new javax.swing.GroupLayout(selectedRiwayatPanel);
        selectedRiwayatPanel.setLayout(selectedRiwayatPanelLayout);
        selectedRiwayatPanelLayout.setHorizontalGroup(
            selectedRiwayatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        selectedRiwayatPanelLayout.setVerticalGroup(
            selectedRiwayatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(selectedRiwayatPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 50));

        selectedHomePanel.setBackground(new java.awt.Color(245, 246, 250));

        javax.swing.GroupLayout selectedHomePanelLayout = new javax.swing.GroupLayout(selectedHomePanel);
        selectedHomePanel.setLayout(selectedHomePanelLayout);
        selectedHomePanelLayout.setHorizontalGroup(
            selectedHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        selectedHomePanelLayout.setVerticalGroup(
            selectedHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(selectedHomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 250, 50));

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 250, 639));

        riwayatPanel.setBackground(new java.awt.Color(245, 246, 250));

        javax.swing.GroupLayout riwayatPanelLayout = new javax.swing.GroupLayout(riwayatPanel);
        riwayatPanel.setLayout(riwayatPanelLayout);
        riwayatPanelLayout.setHorizontalGroup(
            riwayatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, riwayatPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(riwayatTransaksiDokterForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        riwayatPanelLayout.setVerticalGroup(
            riwayatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, riwayatPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(riwayatTransaksiDokterForm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(riwayatPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 810, 640));

        rawatPanel.setBackground(new java.awt.Color(245, 246, 250));

        javax.swing.GroupLayout rawatPanelLayout = new javax.swing.GroupLayout(rawatPanel);
        rawatPanel.setLayout(rawatPanelLayout);
        rawatPanelLayout.setHorizontalGroup(
            rawatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableRawatPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        rawatPanelLayout.setVerticalGroup(
            rawatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableRawatPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        jPanel1.add(rawatPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 810, 640));

        homePanel.setBackground(new java.awt.Color(245, 246, 250));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaLbl19.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        namaLbl19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/healthy-living.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanelDokterGradient3Layout = new javax.swing.GroupLayout(roundedPanelDokterGradient3);
        roundedPanelDokterGradient3.setLayout(roundedPanelDokterGradient3Layout);
        roundedPanelDokterGradient3Layout.setHorizontalGroup(
            roundedPanelDokterGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(namaLbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        roundedPanelDokterGradient3Layout.setVerticalGroup(
            roundedPanelDokterGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLbl19, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        namaLbl6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        namaLbl6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl6.setText("Selesai Perawatan");

        jumlahPasienSelesai.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jumlahPasienSelesai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienSelesai.setText("10 Pasien");

        javax.swing.GroupLayout roundedPanelDokterPutih2Layout = new javax.swing.GroupLayout(roundedPanelDokterPutih2);
        roundedPanelDokterPutih2.setLayout(roundedPanelDokterPutih2Layout);
        roundedPanelDokterPutih2Layout.setHorizontalGroup(
            roundedPanelDokterPutih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelDokterPutih2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(roundedPanelDokterGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanelDokterPutih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLbl6)
                    .addComponent(jumlahPasienSelesai))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        roundedPanelDokterPutih2Layout.setVerticalGroup(
            roundedPanelDokterPutih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterPutih2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundedPanelDokterPutih2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundedPanelDokterPutih2Layout.createSequentialGroup()
                        .addComponent(jumlahPasienSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roundedPanelDokterGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        homePanel.add(roundedPanelDokterPutih2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 192, -1, -1));

        roundedPanelDokter1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaDokterTxt.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        namaDokterTxt.setForeground(new java.awt.Color(255, 255, 255));
        namaDokterTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaDokterTxt.setText("John Cena");
        roundedPanelDokter1.add(namaDokterTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/profile putih.png"))); // NOI18N
        roundedPanelDokter1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 136));

        helloDokterTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        helloDokterTxt.setForeground(new java.awt.Color(255, 255, 255));
        helloDokterTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helloDokterTxt.setText("Hallo Dokter");
        roundedPanelDokter1.add(helloDokterTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 25));

        notelpTxt.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        notelpTxt.setForeground(new java.awt.Color(255, 255, 255));
        notelpTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        notelpTxt.setText("089 642 200 012");
        roundedPanelDokter1.add(notelpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 25));

        tanggalBergabungTxt.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        tanggalBergabungTxt.setForeground(new java.awt.Color(255, 255, 255));
        tanggalBergabungTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tanggalBergabungTxt.setText("23 Juli 2020");
        roundedPanelDokter1.add(tanggalBergabungTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, 25));

        namaLbl14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        namaLbl14.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl14.setText("No Handphone");
        roundedPanelDokter1.add(namaLbl14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 92, 25));

        namaLbl15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        namaLbl15.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl15.setText("Tanggal Bergabung");
        roundedPanelDokter1.add(namaLbl15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 130, 25));

        namaLbl16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        namaLbl16.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl16.setText("Nama Dokter");
        roundedPanelDokter1.add(namaLbl16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 92, 25));

        namaLbl17.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        namaLbl17.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl17.setText("Profile Dokter");
        roundedPanelDokter1.add(namaLbl17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 25));

        homePanel.add(roundedPanelDokter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 52, 380, 250));

        namaLbl18.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        namaLbl18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/timer.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanelDokterGradient1Layout = new javax.swing.GroupLayout(roundedPanelDokterGradient1);
        roundedPanelDokterGradient1.setLayout(roundedPanelDokterGradient1Layout);
        roundedPanelDokterGradient1Layout.setHorizontalGroup(
            roundedPanelDokterGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(namaLbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        roundedPanelDokterGradient1Layout.setVerticalGroup(
            roundedPanelDokterGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLbl18, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        namaLbl3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        namaLbl3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl3.setText("Menunggu Perawatan");

        jumlahPasienTunggu.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jumlahPasienTunggu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienTunggu.setText("5 Pasien");

        javax.swing.GroupLayout roundedPanelDokterPutih1Layout = new javax.swing.GroupLayout(roundedPanelDokterPutih1);
        roundedPanelDokterPutih1.setLayout(roundedPanelDokterPutih1Layout);
        roundedPanelDokterPutih1Layout.setHorizontalGroup(
            roundedPanelDokterPutih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelDokterPutih1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(roundedPanelDokterGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanelDokterPutih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLbl3)
                    .addComponent(jumlahPasienTunggu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanelDokterPutih1Layout.setVerticalGroup(
            roundedPanelDokterPutih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelDokterPutih1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(roundedPanelDokterPutih1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundedPanelDokterGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanelDokterPutih1Layout.createSequentialGroup()
                        .addComponent(jumlahPasienTunggu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        homePanel.add(roundedPanelDokterPutih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 82, 300, -1));

        namaLbl4.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        namaLbl4.setForeground(new java.awt.Color(3, 104, 218));
        namaLbl4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl4.setText("Dashboard> ");
        homePanel.add(namaLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 15, -1, 25));

        namaLbl5.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        namaLbl5.setForeground(new java.awt.Color(3, 104, 218));
        namaLbl5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl5.setText("Home");
        homePanel.add(namaLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 15, 92, 25));

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        homePanel.add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 316, -1, -1));

        tablePasienRawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2", "3", "Selesai", "Selesai"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablePasienRawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePasienRawatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePasienRawat);

        homePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 710, 280));

        jPanel1.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 810, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtn3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitBtn3ActionPerformed

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        // TODO add your handling code here:
        
        
        setPanelSelected(false, false, false);
        LogOut.setForeground(selectedColor);
        Icon icon = new ImageIcon(getClass().getResource("/Aset/logout (1).png"));
        logOutIcon.setIcon(icon);
        selectedLogoutPanel.setVisible(true);
        
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Yakin ingin Log Out ? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
                LoginView mp = new LoginView();
                mp.setVisible(true);
                this.setVisible(false);
            break;

            case 1:
                LogOut.setForeground(defaultColor);
                Icon icon5 = new ImageIcon(getClass().getResource("/Aset/logout.png"));
                logOutIcon.setIcon(icon5);
                homelblMouseClicked(evt);
            break;
        }

    }//GEN-LAST:event_LogOutMouseClicked

    private void LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseEntered
        // TODO add your handling code here:
        panelDashboard.setVisible(true);
        panelDashboard.setLocation(panelDashboard.getX(), 580);
        
    }//GEN-LAST:event_LogOutMouseEntered

    private void LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseExited

    }//GEN-LAST:event_LogOutMouseExited

    private void homelblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelblMouseEntered
        // TODO add your handling code here:
        panelDashboard.setLocation(panelDashboard.getX(), 120);
        
    }//GEN-LAST:event_homelblMouseEntered

    private void rawatLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawatLblMouseEntered
        // TODO add your handling code here:
        panelDashboard.setLocation(panelDashboard.getX(), 180);
    }//GEN-LAST:event_rawatLblMouseEntered

    private void riwayatLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatLblMouseEntered
        // TODO add your handling code here:
        panelDashboard.setLocation(panelDashboard.getX(), 240);
    }//GEN-LAST:event_riwayatLblMouseEntered

    private void rawatLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawatLblMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_rawatLblMouseExited

    private void riwayatLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatLblMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatLblMouseExited

    private void homelblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelblMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_homelblMouseExited

    private void rawatLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rawatLblMouseClicked
        // TODO add your handling code here:
        setPanelSelected(false, true, false);
        homePanel.setVisible(false);
        rawatPanel.setVisible(true);
        riwayatPanel.setVisible(false);
    }//GEN-LAST:event_rawatLblMouseClicked

    private void riwayatLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_riwayatLblMouseClicked
        // TODO add your handling code here:
        setPanelSelected(false, false, true);
    }//GEN-LAST:event_riwayatLblMouseClicked

    private void homelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homelblMouseClicked
        // TODO add your handling code here:
        setPanelSelected(true, false, false);
    }//GEN-LAST:event_homelblMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        setTablePasien();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void tablePasienRawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePasienRawatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePasienRawatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DokterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        
        FlatMacLightLaf.setup();
        UIManager.put( "Button.arc", 999);
        UIManager.put( "Component.arc", 999 );
        UIManager.put( "TextComponent.arc", 999 );
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Staf loginData = new Staf(9, "Dendy", "089643938007", "2023-05-31", "Dokter", "dendy", "dendy");
                new DokterView(loginData).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogOut;
    private javax.swing.JButton exitBtn3;
    private javax.swing.JLabel helloDokterTxt;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel homelbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jumlahPasienSelesai;
    private javax.swing.JLabel jumlahPasienTunggu;
    private javax.swing.JLabel logOutIcon;
    private javax.swing.JLabel namaDokterTxt;
    private javax.swing.JLabel namaLbl14;
    private javax.swing.JLabel namaLbl15;
    private javax.swing.JLabel namaLbl16;
    private javax.swing.JLabel namaLbl17;
    private javax.swing.JLabel namaLbl18;
    private javax.swing.JLabel namaLbl19;
    private javax.swing.JLabel namaLbl2;
    private javax.swing.JLabel namaLbl20;
    private javax.swing.JLabel namaLbl3;
    private javax.swing.JLabel namaLbl4;
    private javax.swing.JLabel namaLbl5;
    private javax.swing.JLabel namaLbl6;
    private javax.swing.JLabel notelpTxt;
    private DokterDashboard.roundedPanelDokterGradientTransparan panelDashboard;
    private javax.swing.JLabel rawatIcon;
    private javax.swing.JLabel rawatLbl;
    private javax.swing.JPanel rawatPanel;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JLabel riwayatIcon;
    private javax.swing.JLabel riwayatLbl;
    private javax.swing.JPanel riwayatPanel;
    private DokterDashboard.RiwayatTransaksiDokterForm riwayatTransaksiDokterForm1;
    private DokterDashboard.roundedPanelDokter roundedPanelDokter1;
    private DokterDashboard.roundedPanelDokterGradient roundedPanelDokterGradient1;
    private DokterDashboard.roundedPanelDokterGradient roundedPanelDokterGradient3;
    private DokterDashboard.roundedPanelDokterPutih roundedPanelDokterPutih1;
    private DokterDashboard.roundedPanelDokterPutih roundedPanelDokterPutih2;
    private DokterDashboard.roundedPanelDokterPutih selectedHomePanel;
    private DokterDashboard.roundedPanelDokterPutih selectedLogoutPanel;
    private DokterDashboard.roundedPanelDokterPutih selectedRawatPanel;
    private DokterDashboard.roundedPanelDokterPutih selectedRiwayatPanel;
    private DokterDashboard.TableDokterCustomStatus tablePasienRawat;
    private DokterDashboard.RawatPasienForm tableRawatPasien;
    private javax.swing.JLabel tanggalBergabungTxt;
    // End of variables declaration//GEN-END:variables


    public void setProfileDokter(){
        namaDokterTxt.setText(loginData.getNama());
        helloDokterTxt.setText("Dokter "+loginData.getNama());
        notelpTxt.setText(loginData.getNo_telepon());
        tanggalBergabungTxt.setText(loginData.getTanggal_bergabung());
        
    }
    
    private void setTablePasien() {
        tablePasienRawat.setModel(transaksiControl.showDataPasienPerDokter(loginData.getId(), "<> 'Menunggu'"));
        jumlahPasienSelesai.setText(transaksiControl.showDataPasienPerDokter(loginData.getId(), "<> 'Menunggu'").getRowCount()+" Pasien");
        jumlahPasienTunggu.setText(transaksiControl.showDataPasienPerDokter(loginData.getId(), "= 'Menunggu'").getRowCount()+" Pasien");
    }

}
