/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DokterDashboard;

import com.formdev.flatlaf.FlatClientProperties;
import control.DetailTransaksiControl;
import control.ObatControl;
import control.TindakanControl;
import control.TransaksiControl;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import model.DetailTransaksi;
import model.Obat;
import model.Staf;
import model.Tindakan;
import model.Transaksi;

/**
 *
 * @author dendy
 */
public class RawatPasienForm extends javax.swing.JPanel {

    /**
     * Creates new form RawatPasienForm
     */
      private TransaksiControl transaksiControl;
    private DetailTransaksiControl detailTransaksiControl;
    private ObatControl obatControl;
    private TindakanControl tindakanControl;
    private List<Obat> listObat;
    private List<Tindakan> listTindakan;
    private int SelectedID = 0;
    private int SelectedIDDetailTransaksi = 0;
    private Staf dataLogin;
    
    public RawatPasienForm() {
        initComponents();
        transaksiControl = new TransaksiControl();
        detailTransaksiControl = new DetailTransaksiControl();
        obatControl = new ObatControl();
        tindakanControl = new TindakanControl();
        diagnosisTxt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Diagnosis");
        namaPasienTxt.putClientProperty(FlatClientProperties.STYLE, ""
                +"borderWidth:0;"
                + "focusWidth:0");
        umurPasienTxt.putClientProperty(FlatClientProperties.STYLE, ""
                +"borderWidth:0;"
                + "focusWidth:0");
        
        setObatTindakanDropdown();
        setTableObatAll();
        setTableObat();
        setTableTindakanAll();
        setTableTindakan();
        setListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameRawatInput = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        diagnosisTxt = new javax.swing.JTextField();
        obatDropdown = new javax.swing.JComboBox<>();
        jumlahObatSpinner = new javax.swing.JSpinner();
        addObatBtn = new javax.swing.JButton();
        tindakanDropdown = new javax.swing.JComboBox<>();
        addTindakanBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTindakan = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableObat = new javax.swing.JTable();
        doneBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        namaPasienLabel = new javax.swing.JLabel();
        umurPasienLabel = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        namaPasienTxt = new javax.swing.JTextField();
        umurPasienTxt = new javax.swing.JTextField();
        showTableObat = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        roundedPanelDokterGradient6 = new DokterDashboard.roundedPanelDokterGradient();
        namaLbl29 = new javax.swing.JLabel();
        back3 = new javax.swing.JLabel();
        namaLbl14 = new javax.swing.JLabel();
        jumlahPasienSelesai6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableObatAll = new DokterDashboard.TableDokterCustom();
        jPanel1 = new javax.swing.JPanel();
        back1 = new javax.swing.JLabel();
        namaLbl12 = new javax.swing.JLabel();
        jumlahPasienSelesai4 = new javax.swing.JLabel();
        roundedPanelDokterGradient3 = new DokterDashboard.roundedPanelDokterGradient();
        namaLbl27 = new javax.swing.JLabel();
        showTableTindakan = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableTindakanAll = new DokterDashboard.TableDokterCustom();
        jPanel5 = new javax.swing.JPanel();
        roundedPanelDokterGradient5 = new DokterDashboard.roundedPanelDokterGradient();
        namaLbl28 = new javax.swing.JLabel();
        back2 = new javax.swing.JLabel();
        namaLbl13 = new javax.swing.JLabel();
        jumlahPasienSelesai5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        refreshBtn1 = new javax.swing.JButton();
        roundedPanelDokterPutih3 = new DokterDashboard.roundedPanelDokterPutih();
        roundedPanelDokterGradient4 = new DokterDashboard.roundedPanelDokterGradient();
        namaLbl21 = new javax.swing.JLabel();
        seeMoreTindakan = new javax.swing.JLabel();
        jumlahPasienSelesai1 = new javax.swing.JLabel();
        roundedPanelDokterPutih4 = new DokterDashboard.roundedPanelDokterPutih();
        roundedPanelDokterGradient2 = new DokterDashboard.roundedPanelDokterGradient();
        namaLbl26 = new javax.swing.JLabel();
        seeMoreObat = new javax.swing.JLabel();
        jumlahPasienTunggu1 = new javax.swing.JLabel();
        namaLbl9 = new javax.swing.JLabel();
        namaLbl10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePasienRawat = new DokterDashboard.TableDokterCustom();
        selectBtn = new javax.swing.JButton();
        jumlahPasienSelesai2 = new javax.swing.JLabel();
        jumlahPasienSelesai3 = new javax.swing.JLabel();
        namaLbl11 = new javax.swing.JLabel();

        frameRawatInput.setUndecorated(true);

        addObatBtn.setText("Add");
        addObatBtn.setEnabled(false);
        addObatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObatBtnActionPerformed(evt);
            }
        });

        addTindakanBtn.setText("Add");
        addTindakanBtn.setEnabled(false);
        addTindakanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTindakanBtnActionPerformed(evt);
            }
        });

        tableTindakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTindakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTindakanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableTindakan);

        tableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableObatMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableObat);

        doneBtn.setText("Done");
        doneBtn.setEnabled(false);
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.setEnabled(false);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        namaPasienLabel.setText("Nama Pasien");

        umurPasienLabel.setText("Umur Pasien");

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        namaPasienTxt.setEditable(false);

        umurPasienTxt.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(doneBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(umurPasienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(namaPasienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(namaPasienTxt)
                                        .addComponent(umurPasienTxt)))
                                .addComponent(diagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(obatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jumlahObatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addObatBtn))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tindakanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addTindakanBtn)))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPasienLabel)
                    .addComponent(namaPasienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umurPasienLabel)
                    .addComponent(umurPasienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(diagnosisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahObatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addObatBtn)
                    .addComponent(tindakanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTindakanBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBtn)
                    .addComponent(doneBtn)
                    .addComponent(cancelBtn))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout frameRawatInputLayout = new javax.swing.GroupLayout(frameRawatInput.getContentPane());
        frameRawatInput.getContentPane().setLayout(frameRawatInputLayout);
        frameRawatInputLayout.setHorizontalGroup(
            frameRawatInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameRawatInputLayout.setVerticalGroup(
            frameRawatInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        showTableObat.setUndecorated(true);
        showTableObat.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(14, 210, 247));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaLbl29.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        namaLbl29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/injection.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanelDokterGradient6Layout = new javax.swing.GroupLayout(roundedPanelDokterGradient6);
        roundedPanelDokterGradient6.setLayout(roundedPanelDokterGradient6Layout);
        roundedPanelDokterGradient6Layout.setHorizontalGroup(
            roundedPanelDokterGradient6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(namaLbl29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        roundedPanelDokterGradient6Layout.setVerticalGroup(
            roundedPanelDokterGradient6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLbl29, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(roundedPanelDokterGradient6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        back3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back3.setForeground(new java.awt.Color(255, 255, 255));
        back3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/next.png"))); // NOI18N
        back3.setText("Back");
        back3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back3MouseClicked(evt);
            }
        });
        jPanel7.add(back3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 80, 40));

        namaLbl14.setForeground(new java.awt.Color(204, 204, 204));
        namaLbl14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl14.setText("Daftar Obat Atma Universal Clinic");
        jPanel7.add(namaLbl14, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 108, 380, 25));

        jumlahPasienSelesai6.setFont(new java.awt.Font("Century Gothic", 1, 32)); // NOI18N
        jumlahPasienSelesai6.setForeground(new java.awt.Color(14, 210, 247));
        jumlahPasienSelesai6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienSelesai6.setText("Daftar Obat Tersedia");
        jPanel7.add(jumlahPasienSelesai6, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 68, 540, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/banner.jpg"))); // NOI18N
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 30, 830, 140));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 150));

        tableObatAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableObatAll);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 692, 360));

        jPanel1.setBackground(new java.awt.Color(14, 210, 247));

        back1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back1.setForeground(new java.awt.Color(255, 255, 255));
        back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/next.png"))); // NOI18N
        back1.setText("Back");
        back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1MouseClicked(evt);
            }
        });

        namaLbl12.setForeground(new java.awt.Color(255, 255, 255));
        namaLbl12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl12.setText("Daftar Obat Atma Universal Clinic");

        jumlahPasienSelesai4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jumlahPasienSelesai4.setForeground(new java.awt.Color(255, 255, 255));
        jumlahPasienSelesai4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienSelesai4.setText("Daftar Obat yang tersedia");

        namaLbl27.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        namaLbl27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/pills.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanelDokterGradient3Layout = new javax.swing.GroupLayout(roundedPanelDokterGradient3);
        roundedPanelDokterGradient3.setLayout(roundedPanelDokterGradient3Layout);
        roundedPanelDokterGradient3Layout.setHorizontalGroup(
            roundedPanelDokterGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(namaLbl27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        roundedPanelDokterGradient3Layout.setVerticalGroup(
            roundedPanelDokterGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLbl27, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(roundedPanelDokterGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaLbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahPasienSelesai4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundedPanelDokterGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(namaLbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jumlahPasienSelesai4))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 150));

        showTableObat.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        showTableTindakan.setUndecorated(true);
        showTableTindakan.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableTindakanAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tableTindakanAll);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 692, 360));

        jPanel5.setBackground(new java.awt.Color(14, 210, 247));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaLbl28.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        namaLbl28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/injection.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanelDokterGradient5Layout = new javax.swing.GroupLayout(roundedPanelDokterGradient5);
        roundedPanelDokterGradient5.setLayout(roundedPanelDokterGradient5Layout);
        roundedPanelDokterGradient5Layout.setHorizontalGroup(
            roundedPanelDokterGradient5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(namaLbl28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        roundedPanelDokterGradient5Layout.setVerticalGroup(
            roundedPanelDokterGradient5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLbl28, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(roundedPanelDokterGradient5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        back2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        back2.setForeground(new java.awt.Color(255, 255, 255));
        back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/next.png"))); // NOI18N
        back2.setText("Back");
        back2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back2MouseClicked(evt);
            }
        });
        jPanel5.add(back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, 80, 40));

        namaLbl13.setForeground(new java.awt.Color(204, 204, 204));
        namaLbl13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl13.setText("Daftar Tindakan Atma Universal Clinic");
        jPanel5.add(namaLbl13, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 108, 380, 25));

        jumlahPasienSelesai5.setFont(new java.awt.Font("Century Gothic", 1, 32)); // NOI18N
        jumlahPasienSelesai5.setForeground(new java.awt.Color(14, 210, 247));
        jumlahPasienSelesai5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienSelesai5.setText("Daftar Tindakan Tersedia");
        jPanel5.add(jumlahPasienSelesai5, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 68, 540, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/banner.jpg"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 30, 830, 140));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 150));

        showTableTindakan.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBackground(new java.awt.Color(245, 246, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshBtn1.setText("Refresh");
        refreshBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtn1ActionPerformed(evt);
            }
        });
        add(refreshBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 282, 90, 30));

        namaLbl21.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        namaLbl21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/injection.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanelDokterGradient4Layout = new javax.swing.GroupLayout(roundedPanelDokterGradient4);
        roundedPanelDokterGradient4.setLayout(roundedPanelDokterGradient4Layout);
        roundedPanelDokterGradient4Layout.setHorizontalGroup(
            roundedPanelDokterGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(namaLbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        roundedPanelDokterGradient4Layout.setVerticalGroup(
            roundedPanelDokterGradient4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLbl21, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        seeMoreTindakan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        seeMoreTindakan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seeMoreTindakan.setText("See More >>");
        seeMoreTindakan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seeMoreTindakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeMoreTindakanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seeMoreTindakanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seeMoreTindakanMouseExited(evt);
            }
        });

        jumlahPasienSelesai1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jumlahPasienSelesai1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienSelesai1.setText("Tindakan");

        javax.swing.GroupLayout roundedPanelDokterPutih3Layout = new javax.swing.GroupLayout(roundedPanelDokterPutih3);
        roundedPanelDokterPutih3.setLayout(roundedPanelDokterPutih3Layout);
        roundedPanelDokterPutih3Layout.setHorizontalGroup(
            roundedPanelDokterPutih3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelDokterPutih3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(roundedPanelDokterGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanelDokterPutih3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seeMoreTindakan)
                    .addComponent(jumlahPasienSelesai1))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        roundedPanelDokterPutih3Layout.setVerticalGroup(
            roundedPanelDokterPutih3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelDokterPutih3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(roundedPanelDokterPutih3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundedPanelDokterPutih3Layout.createSequentialGroup()
                        .addComponent(jumlahPasienSelesai1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seeMoreTindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(roundedPanelDokterGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(roundedPanelDokterPutih3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 300, -1));

        namaLbl26.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        namaLbl26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLbl26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aset/pills.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanelDokterGradient2Layout = new javax.swing.GroupLayout(roundedPanelDokterGradient2);
        roundedPanelDokterGradient2.setLayout(roundedPanelDokterGradient2Layout);
        roundedPanelDokterGradient2Layout.setHorizontalGroup(
            roundedPanelDokterGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(namaLbl26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        roundedPanelDokterGradient2Layout.setVerticalGroup(
            roundedPanelDokterGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanelDokterGradient2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLbl26, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        seeMoreObat.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        seeMoreObat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seeMoreObat.setText("See More>>");
        seeMoreObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seeMoreObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeMoreObatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seeMoreObatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seeMoreObatMouseExited(evt);
            }
        });

        jumlahPasienTunggu1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jumlahPasienTunggu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienTunggu1.setText("Obat");

        javax.swing.GroupLayout roundedPanelDokterPutih4Layout = new javax.swing.GroupLayout(roundedPanelDokterPutih4);
        roundedPanelDokterPutih4.setLayout(roundedPanelDokterPutih4Layout);
        roundedPanelDokterPutih4Layout.setHorizontalGroup(
            roundedPanelDokterPutih4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelDokterPutih4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(roundedPanelDokterGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanelDokterPutih4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahPasienTunggu1)
                    .addGroup(roundedPanelDokterPutih4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(seeMoreObat)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        roundedPanelDokterPutih4Layout.setVerticalGroup(
            roundedPanelDokterPutih4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelDokterPutih4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(roundedPanelDokterPutih4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundedPanelDokterGradient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedPanelDokterPutih4Layout.createSequentialGroup()
                        .addComponent(jumlahPasienTunggu1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seeMoreObat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(roundedPanelDokterPutih4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, 100));

        namaLbl9.setForeground(new java.awt.Color(102, 102, 102));
        namaLbl9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl9.setText("Daftar Pasien yang perlu perawatan");
        add(namaLbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 360, 25));

        namaLbl10.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        namaLbl10.setForeground(new java.awt.Color(3, 104, 218));
        namaLbl10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl10.setText("Rawat Pasien");
        add(namaLbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 190, 25));

        tablePasienRawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePasienRawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePasienRawatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePasienRawat);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 700, 290));

        selectBtn.setBackground(new java.awt.Color(0, 66, 175));
        selectBtn.setForeground(new java.awt.Color(255, 255, 255));
        selectBtn.setText("+ Rawat Sekarang");
        selectBtn.setEnabled(false);
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });
        add(selectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 282, -1, 30));

        jumlahPasienSelesai2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jumlahPasienSelesai2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienSelesai2.setText("Antrean Pasien");
        add(jumlahPasienSelesai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 630, -1));

        jumlahPasienSelesai3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jumlahPasienSelesai3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPasienSelesai3.setText("Obat & Tindakan yang tersedia");
        add(jumlahPasienSelesai3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 631, -1));

        namaLbl11.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        namaLbl11.setForeground(new java.awt.Color(3, 104, 218));
        namaLbl11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaLbl11.setText("Dashboard> ");
        add(namaLbl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void tablePasienRawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePasienRawatMouseClicked

    }//GEN-LAST:event_tablePasienRawatMouseClicked

    private void refreshBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtn1ActionPerformed
      setTableRawatPasien();
        
    }//GEN-LAST:event_refreshBtn1ActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        SelectedID = Integer.parseInt(tablePasienRawat.getModel().getValueAt(tablePasienRawat.getSelectedRow(), 6).toString());

        Transaksi transaksi = transaksiControl.searchTransaksi(SelectedID);
        namaPasienTxt.setText(transaksi.getPasien().getNama());
        umurPasienTxt.setText(transaksi.getPasien().getUmur()+" Tahun");
        tablePasienRawat.setEnabled(false);
        setTableObat();
        setTableTindakan();

        diagnosisTxt.putClientProperty("JComponent.outline", "error");
        frameRawatInput.pack();
        frameRawatInput.setLocationRelativeTo(null);
        frameRawatInput.setVisible(true);
    }//GEN-LAST:event_selectBtnActionPerformed

    private void seeMoreObatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeMoreObatMouseEntered
        // TODO add your handling code here:
        seeMoreObat.setForeground(new Color(3,104,218));
    }//GEN-LAST:event_seeMoreObatMouseEntered

    private void seeMoreObatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeMoreObatMouseExited
        // TODO add your handling code here:
        seeMoreObat.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_seeMoreObatMouseExited

    private void seeMoreTindakanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeMoreTindakanMouseEntered
        // TODO add your handling code here:
        seeMoreTindakan.setForeground(new Color(3,104,218));
    }//GEN-LAST:event_seeMoreTindakanMouseEntered

    private void seeMoreTindakanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeMoreTindakanMouseExited
        // TODO add your handling code here:
        seeMoreTindakan.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_seeMoreTindakanMouseExited

    private void addObatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObatBtnActionPerformed
        Obat obat = (Obat) obatDropdown.getSelectedItem();
        Tindakan tindakan = (Tindakan) tindakanDropdown.getItemAt(0);
        int jumlahObat = (int) jumlahObatSpinner.getValue();
        DetailTransaksi dt = new DetailTransaksi(SelectedID, obat, tindakan, jumlahObat);
        int idDetailTransaksi = detailTransaksiControl.checkDetailSama(SelectedID, obat.getId(), "obat");
        if(idDetailTransaksi==0){//cek jika belum ada detail transaksi dengan obat sama
            detailTransaksiControl.insertDetailTransaksi(dt);
        }else{
            dt.setId_detail_transaksi(idDetailTransaksi);
            detailTransaksiControl.updateDetailTransaksi(dt);
        }
        setTableObat();
        doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty()&&!isTableObatTindakanEmpty());
    }//GEN-LAST:event_addObatBtnActionPerformed

    private void addTindakanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTindakanBtnActionPerformed
        Obat obat = (Obat) obatDropdown.getItemAt(0);
        Tindakan tindakan = (Tindakan) tindakanDropdown.getSelectedItem();
        DetailTransaksi dt = new DetailTransaksi(SelectedID, obat, tindakan, 0);
        int idDetailTransaksi = detailTransaksiControl.checkDetailSama(SelectedID, tindakan.getId(), "tindakan");
        if(idDetailTransaksi==0){//cek jika belum ada detail transaksi dengan obat sama
            detailTransaksiControl.insertDetailTransaksi(dt);
        }else{
            dt.setId_detail_transaksi(idDetailTransaksi);
            detailTransaksiControl.updateDetailTransaksi(dt);
        }
        setTableTindakan();
        doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty()&&!isTableObatTindakanEmpty());
    }//GEN-LAST:event_addTindakanBtnActionPerformed

    private void tableTindakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTindakanMouseClicked
        tableObat.clearSelection();
        SelectedIDDetailTransaksi = Integer.parseInt(tableTindakan.getModel().getValueAt(tableTindakan.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tableTindakanMouseClicked

    private void tableObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableObatMouseClicked
        tableTindakan.clearSelection();
        SelectedIDDetailTransaksi = Integer.parseInt(tableObat.getModel().getValueAt(tableObat.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tableObatMouseClicked

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Selesai merawat "+tablePasienRawat.getModel().getValueAt(tablePasienRawat.getSelectedRow(), 1).toString(),"Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            Transaksi transaksi = transaksiControl.searchTransaksi(SelectedID);
            transaksi.setStatus("Bayar");
            transaksi.setDiagnosis(diagnosisTxt.getText());
            transaksi.setTanggalTransaksi(transaksi.dateTimeNowinString());
            transaksiControl.updateStatusDataTransaksi(transaksi);
            transaksi.setDetailTransaksiList(detailTransaksiControl.getListDetailTransaksiByTransaksiID("", transaksi.getId()));
            for(DetailTransaksi dt : transaksi.getDetailTransaksiList()){
                if(dt.getObat().getId()!=1 && dt.getJumlah_obat()>0){
                    obatControl.updateJumlahObat(dt.getObat().getId(), dt.getJumlah_obat(), "-");
                }
            }
            setTableRawatPasien();
            SelectedID=0;
            setTableObat();
            setTableTindakan();
            tablePasienRawat.setEnabled(true);
            doneBtn.setEnabled(false);
            frameRawatInput.setVisible(false);
            clearAll();
        }
    }//GEN-LAST:event_doneBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        detailTransaksiControl.deleteDetailTransaksi(SelectedIDDetailTransaksi);
        setTableObat();
        setTableTindakan();
        doneBtn.setEnabled(tableObat.getRowCount()!=0||tableTindakan.getRowCount()!=0);
        SelectedIDDetailTransaksi=0;
    }//GEN-LAST:event_removeBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        frameRawatInput.setVisible(false);
        tablePasienRawat.setEnabled(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void seeMoreObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeMoreObatMouseClicked
        // TODO add your handling code here:
        showTableObat.pack();
        showTableObat.setSize(762, 578);
        showTableObat.setLocationRelativeTo(null);
        showTableObat.setVisible(true);
        setTableObatAll();

    }//GEN-LAST:event_seeMoreObatMouseClicked

    private void back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2MouseClicked
        // TODO add your handling code here:
        showTableTindakan.setVisible(false);
    }//GEN-LAST:event_back2MouseClicked

    private void seeMoreTindakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeMoreTindakanMouseClicked
        // TODO add your handling code here:
        showTableTindakan.pack();
        showTableTindakan.setSize(762, 578);
        showTableTindakan.setLocationRelativeTo(null);
        showTableTindakan.setVisible(true);
    }//GEN-LAST:event_seeMoreTindakanMouseClicked

    private void back3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back3MouseClicked
        // TODO add your handling code here:
                showTableObat.setVisible(false);
    }//GEN-LAST:event_back3MouseClicked

    private void back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_back1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addObatBtn;
    private javax.swing.JButton addTindakanBtn;
    private javax.swing.JLabel back1;
    private javax.swing.JLabel back2;
    private javax.swing.JLabel back3;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField diagnosisTxt;
    private javax.swing.JButton doneBtn;
    private javax.swing.JFrame frameRawatInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jumlahObatSpinner;
    private javax.swing.JLabel jumlahPasienSelesai1;
    private javax.swing.JLabel jumlahPasienSelesai2;
    private javax.swing.JLabel jumlahPasienSelesai3;
    private javax.swing.JLabel jumlahPasienSelesai4;
    private javax.swing.JLabel jumlahPasienSelesai5;
    private javax.swing.JLabel jumlahPasienSelesai6;
    private javax.swing.JLabel jumlahPasienTunggu1;
    private javax.swing.JLabel namaLbl10;
    private javax.swing.JLabel namaLbl11;
    private javax.swing.JLabel namaLbl12;
    private javax.swing.JLabel namaLbl13;
    private javax.swing.JLabel namaLbl14;
    private javax.swing.JLabel namaLbl21;
    private javax.swing.JLabel namaLbl26;
    private javax.swing.JLabel namaLbl27;
    private javax.swing.JLabel namaLbl28;
    private javax.swing.JLabel namaLbl29;
    private javax.swing.JLabel namaLbl9;
    private javax.swing.JLabel namaPasienLabel;
    private javax.swing.JTextField namaPasienTxt;
    private javax.swing.JComboBox<Obat> obatDropdown;
    private javax.swing.JButton refreshBtn1;
    private javax.swing.JButton removeBtn;
    private DokterDashboard.roundedPanelDokterGradient roundedPanelDokterGradient2;
    private DokterDashboard.roundedPanelDokterGradient roundedPanelDokterGradient3;
    private DokterDashboard.roundedPanelDokterGradient roundedPanelDokterGradient4;
    private DokterDashboard.roundedPanelDokterGradient roundedPanelDokterGradient5;
    private DokterDashboard.roundedPanelDokterGradient roundedPanelDokterGradient6;
    private DokterDashboard.roundedPanelDokterPutih roundedPanelDokterPutih3;
    private DokterDashboard.roundedPanelDokterPutih roundedPanelDokterPutih4;
    private javax.swing.JLabel seeMoreObat;
    private javax.swing.JLabel seeMoreTindakan;
    private javax.swing.JButton selectBtn;
    private javax.swing.JFrame showTableObat;
    private javax.swing.JFrame showTableTindakan;
    private javax.swing.JTable tableObat;
    private DokterDashboard.TableDokterCustom tableObatAll;
    private DokterDashboard.TableDokterCustom tablePasienRawat;
    private javax.swing.JTable tableTindakan;
    private DokterDashboard.TableDokterCustom tableTindakanAll;
    private javax.swing.JComboBox<Tindakan> tindakanDropdown;
    private javax.swing.JLabel umurPasienLabel;
    private javax.swing.JTextField umurPasienTxt;
    // End of variables declaration//GEN-END:variables

    private void setObatTindakanDropdown() {
        listObat = obatControl.showListObat("");
        obatDropdown.removeAllItems();
        for(Obat o:listObat){
            obatDropdown.addItem(o);
        }
        listTindakan = tindakanControl.showListTindakan("");
        tindakanDropdown.removeAllItems();
        for(Tindakan t : listTindakan){
            tindakanDropdown.addItem(t);
        }
    }
    private void setTableObatAll(){
        tableObatAll.setModel(obatControl.showDataObat(""));
        
        
    }
    private void setTableObat(){
        tableObat.setModel(detailTransaksiControl.showDataKeranjangObat("", SelectedID));
        
    }
    private void setTableTindakanAll(){
        tableTindakanAll.setModel (tindakanControl.showDataTindakan(""));
    }
    
    private void setTableTindakan(){
        tableTindakan.setModel(detailTransaksiControl.showDataKeranjangTindakan("", SelectedID));
        
    }
    
    private void setListener() {
        tablePasienRawat.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    boolean isRowSelected = tablePasienRawat.getSelectedRow() != -1;
                    boolean isColumnSelected = tablePasienRawat.getSelectedColumn() != -1;

                    selectBtn.setEnabled(isRowSelected || isColumnSelected);
                    cancelBtn.setEnabled(isRowSelected || isColumnSelected);
                }
            }
        });
        
        tableObat.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    isTableObatTindakanSelected();
                }
            }
        });
        
        tableTindakan.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    isTableObatTindakanSelected();
                }
            }
        });
        
        jumlahObatSpinner.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int value = (int) jumlahObatSpinner.getValue();
                if(value<0){
                    jumlahObatSpinner.setValue(0);
                }else{
                    isObatSelected();
                }
            }
        });
        
        obatDropdown.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                isObatSelected();
            }
        });
        
        tindakanDropdown.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addTindakanBtn.setEnabled(tindakanDropdown.getSelectedIndex()!=0);
            }
        });
        
        diagnosisTxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                if(!diagnosisTxt.getText().isEmpty()){
                    diagnosisTxt.putClientProperty("JComponent.outline", "#FF000");
                }else{
                    diagnosisTxt.putClientProperty("JComponent.outline", "error");
                }
                doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty()&&!isTableObatTindakanEmpty());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if(!diagnosisTxt.getText().isEmpty()){
                    diagnosisTxt.putClientProperty("JComponent.outline", "#FF000");
                }else{
                    diagnosisTxt.putClientProperty("JComponent.outline", "error");
                }
                doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty()&&!isTableObatTindakanEmpty());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                if(!diagnosisTxt.getText().isEmpty()){
                    diagnosisTxt.putClientProperty("JComponent.outline", "#FF000");
                    doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty());
                }else{
                    diagnosisTxt.putClientProperty("JComponent.outline", "error");
                }
                doneBtn.setEnabled(!diagnosisTxt.getText().isEmpty()&&!isTableObatTindakanEmpty());
            }
        });
        
    }
    private boolean isTableObatTindakanEmpty(){
        return (tableObat.getRowCount()==0&&tableTindakan.getRowCount()==0);
    }
    private void isTableObatTindakanSelected(){
        removeBtn.setEnabled(tableObat.getSelectedRow()!=-1 || tableTindakan.getSelectedRow()!=-1);
    }
    private void isObatSelected(){
        addObatBtn.setEnabled((int)jumlahObatSpinner.getValue()>0 && obatDropdown.getSelectedIndex()!=0);
    }

    public void setDataLogin (Staf login){
        this.dataLogin = login;
    }
    
    public void setTableRawatPasien() {
        tablePasienRawat.setModel(transaksiControl.showDataPasienPerDokter(dataLogin.getId(), "= 'Menunggu'"));
        
    }
    
    public void clearAll(){
        setTableObat();
        setTableTindakan();
        setObatTindakanDropdown();
        diagnosisTxt.setText("");
        jumlahObatSpinner.setValue(0);
    }
    

}
