/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.Staf;

/**
 *
 * @author VICTUS
 */
public class KasirView extends javax.swing.JFrame {

    /**
     * Creates new form KasirView
     */
    Color defaultColor, selectedColor;
    public KasirView(Staf loginData) {
        initComponents();
        defaultColor = new Color(0,0,102);
        selectedColor = new Color(255,153,51);
        periksaMenu.setBackground(defaultColor);
        bayarMenu.setBackground(defaultColor);
        credential.setText(loginData.getNama());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        credential = new javax.swing.JLabel();
        menuBar = new javax.swing.JPanel();
        periksaMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bayarMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CustomerMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        containerView = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 51));

        header.setBackground(new java.awt.Color(255, 153, 51));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("KLINIK KESEHATAN");

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons_logout.png"))); // NOI18N
        logoutBtn.setText(" Logout");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        credential.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        credential.setForeground(new java.awt.Color(255, 255, 255));
        credential.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-male-user-50.png"))); // NOI18N
        credential.setText("Nama");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(credential, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBtn)
                    .addComponent(Title))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(credential)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBar.setBackground(new java.awt.Color(0, 0, 102));
        menuBar.setPreferredSize(new java.awt.Dimension(200, 0));

        periksaMenu.setBackground(new java.awt.Color(0, 0, 102));
        periksaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                periksaMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                periksaMenuMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Periksa");

        javax.swing.GroupLayout periksaMenuLayout = new javax.swing.GroupLayout(periksaMenu);
        periksaMenu.setLayout(periksaMenuLayout);
        periksaMenuLayout.setHorizontalGroup(
            periksaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, periksaMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        periksaMenuLayout.setVerticalGroup(
            periksaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periksaMenuLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        bayarMenu.setBackground(new java.awt.Color(0, 0, 102));
        bayarMenu.setForeground(new java.awt.Color(255, 255, 255));
        bayarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayarMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bayarMenuMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bayar");

        javax.swing.GroupLayout bayarMenuLayout = new javax.swing.GroupLayout(bayarMenu);
        bayarMenu.setLayout(bayarMenuLayout);
        bayarMenuLayout.setHorizontalGroup(
            bayarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bayarMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bayarMenuLayout.setVerticalGroup(
            bayarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bayarMenuLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        CustomerMenu.setBackground(new java.awt.Color(0, 0, 102));
        CustomerMenu.setForeground(new java.awt.Color(255, 255, 255));
        CustomerMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerMenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustomerMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CustomerMenuMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Customer");

        javax.swing.GroupLayout CustomerMenuLayout = new javax.swing.GroupLayout(CustomerMenu);
        CustomerMenu.setLayout(CustomerMenuLayout);
        CustomerMenuLayout.setHorizontalGroup(
            CustomerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerMenuLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        CustomerMenuLayout.setVerticalGroup(
            CustomerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerMenuLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(periksaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bayarMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CustomerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(periksaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bayarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CustomerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        menuBarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CustomerMenu, bayarMenu, periksaMenu});

        containerView.setPreferredSize(new java.awt.Dimension(1000, 620));

        javax.swing.GroupLayout containerViewLayout = new javax.swing.GroupLayout(containerView);
        containerView.setLayout(containerViewLayout);
        containerViewLayout.setHorizontalGroup(
            containerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        containerViewLayout.setVerticalGroup(
            containerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(containerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(containerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void periksaMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_periksaMenuMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_periksaMenuMousePressed

    private void bayarMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarMenuMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bayarMenuMousePressed

    private void periksaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_periksaMenuMouseClicked
        // TODO add your handling code here:
        periksaMenu.setBackground(selectedColor);
        bayarMenu.setBackground(defaultColor);
        CustomerMenu.setBackground(defaultColor);
        PeriksaView periksaView = new PeriksaView();
        containerView.removeAll();
        containerView.add(periksaView).setVisible(true);
        
    }//GEN-LAST:event_periksaMenuMouseClicked

    private void bayarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarMenuMouseClicked
        // TODO add your handling code here:
        periksaMenu.setBackground(defaultColor);
        bayarMenu.setBackground(selectedColor);
        CustomerMenu.setBackground(defaultColor);
        BayarView bayarView = new BayarView();
        containerView.removeAll();
        containerView.add(bayarView).setVisible(true);
    }//GEN-LAST:event_bayarMenuMouseClicked

    private void CustomerMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMenuMouseClicked
        // TODO add your handling code here:
        periksaMenu.setBackground(defaultColor);
        bayarMenu.setBackground(defaultColor);
        CustomerMenu.setBackground(selectedColor);
        CustomerView customerView = new CustomerView();
        containerView.removeAll();
        containerView.add(customerView).setVisible(true);
    }//GEN-LAST:event_CustomerMenuMouseClicked

    private void CustomerMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMenuMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CustomerMenuMousePressed

    private void CustomerMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMenuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerMenuMouseReleased

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Apakah yakin ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        switch(getAnswer){
            case 0:
                LoginView loginView = new LoginView();
                this.dispose();
                loginView.setLocationRelativeTo(null);
                loginView.setVisible(true);
            break;
            case 1:
            break;
        }
        
    }//GEN-LAST:event_logoutBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerMenu;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel bayarMenu;
    private javax.swing.JDesktopPane containerView;
    private javax.swing.JLabel credential;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel periksaMenu;
    // End of variables declaration//GEN-END:variables
}
