/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import control.ObatControl;
import control.PengadaanControl;
import control.SupplierControl;
import exception.InputKosongException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import model.Obat;
import model.Pengadaan;
import model.Supplier;

/**
 *
 * @author VICTUS
 */
public class PengadaanForm extends javax.swing.JFrame {

    /**
     * Creates new form PengadaanForm
     */
    private PengadaanControl pengadaanControl;
    private SupplierControl supplierControl;
    private ObatControl obatControl;
    private List<Supplier> listSupplier;
    private List<Obat> listObat;
    private Pengadaan pengadaan;
    private Obat obat;
    private Supplier supplier;
    private int selectedIndexObat=0;
    private int selectedIndexSupplier=0;
    public PengadaanForm() {
        initComponents();
        pengadaanControl = new PengadaanControl();
        supplierControl = new SupplierControl();
        obatControl = new ObatControl();
        setTablePengadaan();
        setObatDropdown();
        setSupplierDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTab = new javax.swing.JTabbedPane();
        inputTab = new javax.swing.JPanel();
        supplierTab = new javax.swing.JTabbedPane();
        oldSupplierTab = new javax.swing.JPanel();
        supplierDropDown = new javax.swing.JComboBox<>();
        newSupplierTab = new javax.swing.JPanel();
        namaSupplier = new javax.swing.JTextField();
        notelpSupplier = new javax.swing.JTextField();
        emailSupplier = new javax.swing.JTextField();
        ObatTab = new javax.swing.JTabbedPane();
        oldObatTab = new javax.swing.JPanel();
        ObatDropdown = new javax.swing.JComboBox<>();
        newObatTab = new javax.swing.JPanel();
        namaObat = new javax.swing.JTextField();
        hargaObat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jumlahObat = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        tableTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePengadaan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout oldSupplierTabLayout = new javax.swing.GroupLayout(oldSupplierTab);
        oldSupplierTab.setLayout(oldSupplierTabLayout);
        oldSupplierTabLayout.setHorizontalGroup(
            oldSupplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oldSupplierTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supplierDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        oldSupplierTabLayout.setVerticalGroup(
            oldSupplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oldSupplierTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(supplierDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        supplierTab.addTab("Old", oldSupplierTab);

        namaSupplier.setText("Nama");

        notelpSupplier.setText("No Telepon");

        emailSupplier.setText("Email");

        javax.swing.GroupLayout newSupplierTabLayout = new javax.swing.GroupLayout(newSupplierTab);
        newSupplierTab.setLayout(newSupplierTabLayout);
        newSupplierTabLayout.setHorizontalGroup(
            newSupplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSupplierTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(newSupplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaSupplier)
                    .addComponent(notelpSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(emailSupplier))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        newSupplierTabLayout.setVerticalGroup(
            newSupplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSupplierTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(namaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(notelpSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        supplierTab.addTab("New", newSupplierTab);

        javax.swing.GroupLayout oldObatTabLayout = new javax.swing.GroupLayout(oldObatTab);
        oldObatTab.setLayout(oldObatTabLayout);
        oldObatTabLayout.setHorizontalGroup(
            oldObatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oldObatTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ObatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        oldObatTabLayout.setVerticalGroup(
            oldObatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oldObatTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ObatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        ObatTab.addTab("Old", oldObatTab);

        namaObat.setText("Nama");

        hargaObat.setText("Harga");

        javax.swing.GroupLayout newObatTabLayout = new javax.swing.GroupLayout(newObatTab);
        newObatTab.setLayout(newObatTabLayout);
        newObatTabLayout.setHorizontalGroup(
            newObatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newObatTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newObatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaObat)
                    .addComponent(hargaObat, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        newObatTabLayout.setVerticalGroup(
            newObatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newObatTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(namaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hargaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        ObatTab.addTab("New", newObatTab);

        jLabel1.setText("Supplier");

        jLabel2.setText("Obat");

        jLabel3.setText("Jumlah");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputTabLayout = new javax.swing.GroupLayout(inputTab);
        inputTab.setLayout(inputTabLayout);
        inputTabLayout.setHorizontalGroup(
            inputTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputTabLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(inputTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahObat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addBtn)
                .addGap(68, 68, 68))
            .addGroup(inputTabLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(supplierTab, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(ObatTab, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        inputTabLayout.setVerticalGroup(
            inputTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputTabLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(inputTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(inputTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supplierTab)
                    .addComponent(ObatTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(inputTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(jLabel3)
                    .addComponent(jumlahObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        mainTab.addTab("Input", inputTab);

        tablePengadaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePengadaan);

        javax.swing.GroupLayout tableTabLayout = new javax.swing.GroupLayout(tableTab);
        tableTab.setLayout(tableTabLayout);
        tableTabLayout.setHorizontalGroup(
            tableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableTabLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        tableTabLayout.setVerticalGroup(
            tableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableTabLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        mainTab.addTab("Table", tableTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        int supplierSelectedTab = supplierTab.getSelectedIndex();
        int obatSelectedTab = ObatTab.getSelectedIndex();
        supplier = getSupplier(supplierSelectedTab);
        obat = getObat(obatSelectedTab);
        if(supplier!=null && obat!=null){
            LocalDateTime currentDateTime = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String sqlDateTime = currentDateTime.format(formatter);
            try{
                int jumlah_obat = (int) jumlahObat.getValue();
                if(jumlah_obat > 0){
                   pengadaan = new Pengadaan(obat.getId(),supplier.getIdSupplier(),jumlah_obat, sqlDateTime);
                    pengadaanControl.insertDataPengadaan(pengadaan);
                    Obat o = obatControl.searchObat(obat.getNama());
                    o.setStok(obat.getStok()+(int) jumlahObat.getValue());
                    obatControl.updateDataObat(o);
                    setTablePengadaan(); 
                }else{
                    JOptionPane.showConfirmDialog(rootPane, "Jumlah obat harus angka diatas 0","Error",JOptionPane.DEFAULT_OPTION);
                }
                
            }catch(NumberFormatException e){
                JOptionPane.showConfirmDialog(rootPane, "Jumlah obat harus angka diatas 0","Error",JOptionPane.DEFAULT_OPTION);
            }
            
        }
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        FlatMacLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengadaanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Obat> ObatDropdown;
    private javax.swing.JTabbedPane ObatTab;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField emailSupplier;
    private javax.swing.JTextField hargaObat;
    private javax.swing.JPanel inputTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jumlahObat;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JTextField namaObat;
    private javax.swing.JTextField namaSupplier;
    private javax.swing.JPanel newObatTab;
    private javax.swing.JPanel newSupplierTab;
    private javax.swing.JTextField notelpSupplier;
    private javax.swing.JPanel oldObatTab;
    private javax.swing.JPanel oldSupplierTab;
    private javax.swing.JComboBox<Supplier> supplierDropDown;
    private javax.swing.JTabbedPane supplierTab;
    private javax.swing.JTable tablePengadaan;
    private javax.swing.JPanel tableTab;
    // End of variables declaration//GEN-END:variables

    private void setTablePengadaan() {
        tablePengadaan.setModel(pengadaanControl.getTableSuplier(""));
    }

    private void setObatDropdown() {
        listObat = obatControl.showListObat("");
        for(int i=1;i<listObat.size();i++){
            ObatDropdown.addItem(listObat.get(i));
        }
    }

    private void setSupplierDropdown() {
       listSupplier = supplierControl.getListSupplier("");
        for(int i=0;i<listSupplier.size();i++){
            supplierDropDown.addItem(listSupplier.get(i));
        } 
    }

    private Supplier getSupplier(int selectedTab) {
        Supplier s = null;
        if(selectedTab==0){
            selectedIndexSupplier = supplierDropDown.getSelectedIndex();
            s = listSupplier.get(selectedIndexSupplier);
        }else{
            if(supplierControl.searchSupplier(namaSupplier.getText())!=null
//                    || supplierControl.searchSupplier(notelpSupplier.getText())!=null
//                    || supplierControl.searchSupplier(emailSupplier.getText())!=null
              ){
                JOptionPane.showConfirmDialog(rootPane, "Supplier sudah terdaftar","Warning",JOptionPane.DEFAULT_OPTION);
                return null;
            }
            try{
                inputKosongExceptionSupplier();
                s = new Supplier(namaSupplier.getText(), notelpSupplier.getText(), emailSupplier.getText());
                supplierControl.insertDataSupplier(s);
                s = supplierControl.searchSupplier(namaSupplier.getText());
            }catch(InputKosongException e){
                JOptionPane.showMessageDialog(rootPane, e.message());
            }
            
        }
        return s;
    }

    private Obat getObat(int selectedTab) {
        Obat o = null;
        if(selectedTab==0){
            selectedIndexObat = ObatDropdown.getSelectedIndex()+1;//karena di database ada data 1 obat tidak ada
            o = listObat.get(selectedIndexObat);
        }else{
            if(obatControl.searchObat(namaObat.getText())!=null){
                JOptionPane.showConfirmDialog(rootPane, "Obat sudah terdaftar","Warning",JOptionPane.DEFAULT_OPTION);
                return null;
            }
            try{
                inputKosongExceptionObat();
                if(Double.parseDouble(hargaObat.getText())>0){
                    o = new Obat(namaObat.getText(), Double.parseDouble(hargaObat.getText()), 0);
                    obatControl.insertDataObat(o);
                    o = obatControl.searchObat(namaObat.getText()); 
                }
            }catch(InputKosongException e){
                JOptionPane.showMessageDialog(rootPane, e.message());
            }catch(NumberFormatException nfe){
                JOptionPane.showConfirmDialog(rootPane, "Harga obat harus angka diatas 0","Error",JOptionPane.DEFAULT_OPTION);
            }
        }
        return o;
    }

    private void inputKosongExceptionSupplier() throws InputKosongException{
        if(namaSupplier.getText().isEmpty() || notelpSupplier.getText().isEmpty() || emailSupplier.getText().isEmpty()){
            throw new InputKosongException();
        }
    }

    private void inputKosongExceptionObat() throws InputKosongException{
        if(namaObat.getText().isEmpty()){
            throw new InputKosongException();
        }
    }
    
}
