/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminDashboard;

import com.formdev.flatlaf.FlatClientProperties;
import control.MutasiControl;
import javax.swing.JComponent;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author dendy
 */
public class MutasiPanelNew extends javax.swing.JPanel implements IPanelAdmin{

    /**
     * Creates new form MutasiPanelNew
     */
    private MutasiControl mutasiControl;
    public MutasiPanelNew() {
        initComponents();
        mutasiControl = new MutasiControl();
        saldoKlinikTxt.setText("Saldo Klinik  :Rp "+mutasiControl.getSaldo());
        searchTxt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Cari");
        setBorderandFocus(searchTxt);
        
    }

    private void setTableMutasi(String query) {
        tableMutasi.setModel(mutasiControl.getTableMutasi(query));
    }
    
     private void setListener() {
        searchTxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setTableMutasi(searchTxt.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setTableMutasi(searchTxt.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setTableMutasi(searchTxt.getText());
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableMutasi = new KasirDashboard.TableCustom();
        refreshBtn = new javax.swing.JButton();
        saldoKlinikTxt = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableMutasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableMutasi);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 790, 420));

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        saldoKlinikTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saldoKlinikTxt.setText("Saldo Klinik");
        add(saldoKlinikTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 360, 30));
        add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        refreshData();
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JLabel saldoKlinikTxt;
    private javax.swing.JTextField searchTxt;
    private KasirDashboard.TableCustom tableMutasi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refreshData() {
        setTableMutasi("");
        saldoKlinikTxt.setText("Saldo Klinik : Rp "+mutasiControl.getSaldo());
    }
     private void setBorderandFocus(JComponent comp){
        comp.putClientProperty(FlatClientProperties.STYLE, ""
                +"borderWidth:1;"
                + "focusWidth:0");
    }
}
