/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminDashboard;

import com.formdev.flatlaf.FlatClientProperties;
import control.ObatControl;
import exception.InputKosongException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import model.Obat;

/**
 *
 * @author VICTUS
 */
public class ObatPanel extends javax.swing.JPanel implements IPanelAdmin{

    private ObatControl obatControl;
    private List<Obat> listObat;
    private int selectedID;
    public ObatPanel() {
        initComponents();
        obatControl = new ObatControl();
//        namaObatTxt1.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nama obat");
//        hargaObatTxt1.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Harga obat");
        searchTxt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Cari");
//        setBorderandFocus(namaObatTxt1);
//        setBorderandFocus(hargaObatTxt1);
        setBorderandFocus(searchTxt);
        try{
            inputKosongException();
        }catch(InputKosongException e){
            System.out.println(e.message());
        }finally{
            setTableObat("");
            setListener();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableObat = new KasirDashboard.TableCustom();
        searchTxt = new javax.swing.JTextField();
        jumlahObatSpinner = new javax.swing.JSpinner();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        hargaObatTxt = new KasirDashboard.CustomePalette.TextField();
        namaObatTxt = new KasirDashboard.CustomePalette.TextField();
        tanggalMulaiKerjaLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableObatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableObat);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 60, 470, 300));
        add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 270, -1));
        add(jumlahObatSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 161, -1));

        addBtn.setText("Add");
        addBtn.setEnabled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 22, -1, 30));

        editBtn.setText("Edit");
        editBtn.setEnabled(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 22, -1, 30));

        delBtn.setText("Delete");
        delBtn.setEnabled(false);
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });
        add(delBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 22, -1, 30));

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        hargaObatTxt.setLabelText("Harga Obat");
        add(hargaObatTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, -1));

        namaObatTxt.setLabelText("Nama Obat");
        add(namaObatTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, -1));

        tanggalMulaiKerjaLabel.setForeground(new java.awt.Color(51, 51, 51));
        tanggalMulaiKerjaLabel.setText(" Stok Obat");
        add(tanggalMulaiKerjaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        Obat obat = new Obat(namaObatTxt.getText(), Double.parseDouble(hargaObatTxt.getText()), (int) jumlahObatSpinner.getValue());
        if(checkObatSama(obat)){
            JOptionPane.showConfirmDialog(this, "Obat sudah terdaftar","Error",JOptionPane.PLAIN_MESSAGE,JOptionPane.ERROR_MESSAGE);
            clearAll();
            searchTxt.setText(obat.getNama());
        }else{
            obatControl.insertDataObat(obat);
            setTableObat("");
            clearAll();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin hapus "+tableObat.getModel().getValueAt(tableObat.getSelectedRow(), 1).toString()+"?","Warning",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(confirm==JOptionPane.YES_OPTION){
            obatControl.deleteObat(selectedID);
            setTableObat("");
            clearAll();
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearAll();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        Obat obat = new Obat(selectedID,namaObatTxt.getText(), Double.parseDouble(hargaObatTxt.getText()), (int) jumlahObatSpinner.getValue());
        obatControl.updateDataObat(obat);
        setTableObat("");
        clearAll();
    }//GEN-LAST:event_editBtnActionPerformed

    private void tableObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableObatMouseClicked
        // TODO add your handling code here:
        int clickedRow = tableObat.getSelectedRow();
        TableModel tableModel = tableObat.getModel();
        selectedID = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        namaObatTxt.setText(tableModel.getValueAt(clickedRow, 1).toString());
        hargaObatTxt.setText(tableModel.getValueAt(clickedRow, 2).toString());
        jumlahObatSpinner.setValue(tableModel.getValueAt(clickedRow, 3));
    }//GEN-LAST:event_tableObatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private KasirDashboard.CustomePalette.TextField hargaObatTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jumlahObatSpinner;
    private KasirDashboard.CustomePalette.TextField namaObatTxt;
    private javax.swing.JTextField searchTxt;
    private KasirDashboard.TableCustom tableObat;
    private javax.swing.JLabel tanggalMulaiKerjaLabel;
    // End of variables declaration//GEN-END:variables

    private void setTableObat(String query) {
        tableObat.setModel(obatControl.showDataObat(query));
        listObat = obatControl.showListObat("");
    }

    private void setListener() {
        searchTxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setTableObat(searchTxt.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setTableObat(searchTxt.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setTableObat(searchTxt.getText());
            }
        });
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkFields();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkFields();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkFields();
            }

            
        };
        namaObatTxt.getDocument().addDocumentListener(docListener);
        hargaObatTxt.getDocument().addDocumentListener(docListener);
        
        jumlahObatSpinner.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int value = (int) jumlahObatSpinner.getValue();
                if(value<0){
                    jumlahObatSpinner.setValue(0);
                }
                checkFields();
            }
        });
        
        tableObat.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()){
                    checkFields();
                }
            }
        });
    }

    @Override
    public void refreshData() {
        setTableObat("");
        clearAll();
    }
    
    private void checkFields() {
        try{
            inputKosongException();
            int jumlah = (int) jumlahObatSpinner.getValue();
            Double harga = Double.parseDouble(hargaObatTxt.getText());
            addBtn.setEnabled(jumlah>0&&harga>0 && tableObat.getSelectedRow()==-1);
            editBtn.setEnabled(jumlah>0&&harga>0 && tableObat.getSelectedRow()!=-1);
            delBtn.setEnabled(tableObat.getSelectedRow()!=-1);
        }catch(InputKosongException ex){
            addBtn.setEnabled(false);
            editBtn.setEnabled(false);
        }catch(NumberFormatException nfe){
            addBtn.setEnabled(false);
            editBtn.setEnabled(false);
        }
        catch(Exception e){
            addBtn.setEnabled(false);
            editBtn.setEnabled(false);
        }
    }
    
    private void inputKosongException() throws InputKosongException{
        if(namaObatTxt.getText().isEmpty() || hargaObatTxt.getText().isEmpty()){
            throw new InputKosongException();
        }
    }

    private void clearAll() {
        tableObat.clearSelection();
        searchTxt.setText("");
        namaObatTxt.setText("");
        hargaObatTxt.setText("");
        jumlahObatSpinner.setValue(0);
        addBtn.setEnabled(false);
        editBtn.setEnabled(false);
        delBtn.setEnabled(false);
    }
    
    private Boolean checkObatSama(Obat obat){
        for (Obat o : listObat){
            if(o.getNama().equalsIgnoreCase(obat.getNama())){
                return true;
            }
        }
        return false;
    }
    private void setBorderandFocus(JComponent comp){
        comp.putClientProperty(FlatClientProperties.STYLE, ""
                +"borderWidth:1;"
                + "focusWidth:0");
    }
}
