/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AdminDashboard;

import com.formdev.flatlaf.FlatClientProperties;
import control.MutasiControl;
import control.ObatControl;
import control.PengadaanControl;
import control.SupplierControl;
import exception.InputKosongException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import model.Mutasi;
import model.Obat;
import model.Pengadaan;
import model.Supplier;
import utils.UtilTable;

/**
 *
 * @author VICTUS
 */
public class PengadaanPanel extends javax.swing.JPanel implements IPanelAdmin {

    private MutasiControl mutasiControl;
    private PengadaanControl pengadaanControl;
    private SupplierControl supplierControl;
    private ObatControl obatControl;
    private List<Supplier> listSupplier;
    private List<Obat> listObat;
    private Pengadaan pengadaan;
    private Obat obat;
    private Supplier supplier;
    private int selectedIndexObat=0;
    private int selectedIndexSupplier=0;
    
    public PengadaanPanel() {
        initComponents();
        namaObat.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nama Obat");
        hargaObat.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Harga");
        namaSupplier.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nama Supplier");
        notelpSupplier.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "No Telepon");
        emailSupplier.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Email");
        searchTxt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Cari");
        setBorderandFocus(namaObat);
        setBorderandFocus(hargaObat);
        setBorderandFocus(namaSupplier);
        setBorderandFocus(notelpSupplier);
        setBorderandFocus(emailSupplier);
        setBorderandFocus(searchTxt);
        setBorderandFocus(saldoKlinikTxt);
        setBorderandFocus(totalHargaTxt);
        
        mutasiControl = new MutasiControl();
        pengadaanControl = new PengadaanControl();
        supplierControl = new SupplierControl();
        obatControl = new ObatControl();
        saldoKlinikTxt.setText("Rp. "+mutasiControl.getSaldo());
        try{
            inputKosongException();
            
        }catch(InputKosongException e){
            System.out.println(e.message());
        }finally{
            setTablePengadaan("");
            setObatDropdown();
            setSupplierDropdown();
            setListener();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pengadaanTab = new javax.swing.JTabbedPane();
        obatPanel1 = new AdminDashboard.ObatPanel();
        inputTab = new javax.swing.JPanel();
        supplierTab = new javax.swing.JTabbedPane();
        oldSupplierTab = new javax.swing.JPanel();
        supplierDropDown = new javax.swing.JComboBox<>();
        newSupplierTab = new javax.swing.JPanel();
        namaSupplier = new javax.swing.JTextField();
        notelpSupplier = new javax.swing.JTextField();
        emailSupplier = new javax.swing.JTextField();
        ObatTab = new javax.swing.JTabbedPane();
        oldObatTab = new javax.swing.JPanel();
        ObatDropdown = new javax.swing.JComboBox<>();
        newObatTab = new javax.swing.JPanel();
        namaObat = new javax.swing.JTextField();
        hargaObat = new javax.swing.JTextField();
        totalHargaTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        saldoKlinikTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jumlahObat = new javax.swing.JSpinner();
        riwayatTab = new javax.swing.JPanel();
        searchTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePengadaan = new KasirDashboard.TableCustom();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pengadaanTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        pengadaanTab.addTab("Obat", obatPanel1);

        inputTab.setBackground(new java.awt.Color(255, 255, 255));
        inputTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierTab.setBackground(new java.awt.Color(255, 255, 255));

        oldSupplierTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oldSupplierTabLayout = new javax.swing.GroupLayout(oldSupplierTab);
        oldSupplierTab.setLayout(oldSupplierTabLayout);
        oldSupplierTabLayout.setHorizontalGroup(
            oldSupplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oldSupplierTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supplierDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        oldSupplierTabLayout.setVerticalGroup(
            oldSupplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oldSupplierTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(supplierDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        supplierTab.addTab("Old", oldSupplierTab);

        newSupplierTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout newSupplierTabLayout = new javax.swing.GroupLayout(newSupplierTab);
        newSupplierTab.setLayout(newSupplierTabLayout);
        newSupplierTabLayout.setHorizontalGroup(
            newSupplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSupplierTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(newSupplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaSupplier)
                    .addComponent(notelpSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(emailSupplier))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        newSupplierTabLayout.setVerticalGroup(
            newSupplierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newSupplierTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(namaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(notelpSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        supplierTab.addTab("New", newSupplierTab);

        inputTab.add(supplierTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 170));

        ObatTab.setBackground(new java.awt.Color(255, 255, 255));

        oldObatTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout oldObatTabLayout = new javax.swing.GroupLayout(oldObatTab);
        oldObatTab.setLayout(oldObatTabLayout);
        oldObatTabLayout.setHorizontalGroup(
            oldObatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oldObatTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ObatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        oldObatTabLayout.setVerticalGroup(
            oldObatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oldObatTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ObatDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        ObatTab.addTab("Old", oldObatTab);

        newObatTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout newObatTabLayout = new javax.swing.GroupLayout(newObatTab);
        newObatTab.setLayout(newObatTabLayout);
        newObatTabLayout.setHorizontalGroup(
            newObatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newObatTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newObatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaObat)
                    .addComponent(hargaObat, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        newObatTabLayout.setVerticalGroup(
            newObatTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newObatTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(namaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hargaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        ObatTab.addTab("New", newObatTab);

        inputTab.add(ObatTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        totalHargaTxt.setEditable(false);
        totalHargaTxt.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        totalHargaTxt.setText("Rp 0.0");
        totalHargaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaTxtActionPerformed(evt);
            }
        });
        inputTab.add(totalHargaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 160, 30));

        addBtn.setText("Add");
        addBtn.setEnabled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        inputTab.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Saldo Klinik");
        inputTab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 30));

        saldoKlinikTxt.setEditable(false);
        saldoKlinikTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saldoKlinikTxt.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        saldoKlinikTxt.setText("Rp 0");
        saldoKlinikTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoKlinikTxtActionPerformed(evt);
            }
        });
        inputTab.add(saldoKlinikTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 200, 30));

        jPanel2.setBackground(new java.awt.Color(3, 104, 218));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Supplier");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Obat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        inputTab.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 780, 40));

        jLabel6.setText("Total Harga");
        inputTab.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 70, 20));

        jLabel3.setText("Jumlah");
        inputTab.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));
        inputTab.add(jumlahObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 70, 30));

        pengadaanTab.addTab("Pengadaan", inputTab);

        riwayatTab.setBackground(new java.awt.Color(255, 255, 255));
        riwayatTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        riwayatTab.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 20, 290, -1));

        tablePengadaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablePengadaan);

        riwayatTab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 740, 360));

        pengadaanTab.addTab("Riwayat", riwayatTab);

        add(pengadaanTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        int supplierSelectedTab = supplierTab.getSelectedIndex();
        int obatSelectedTab = ObatTab.getSelectedIndex();
        supplier = getSupplier(supplierSelectedTab);
        obat = getObat(obatSelectedTab);
        if(supplier!=null && obat!=null){
            LocalDateTime currentDateTime = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String sqlDateTime = currentDateTime.format(formatter);
            try{
                int jumlah_obat = (int) jumlahObat.getValue();
                if(jumlah_obat > 0){
                    //add pengadaan obat
                    pengadaan = new Pengadaan(obat.getId(),supplier.getIdSupplier(),jumlah_obat, sqlDateTime);
                    pengadaanControl.insertDataPengadaan(pengadaan);
                    //Update Obat
                    obatControl.updateJumlahObat(obat.getId(), jumlah_obat, "+");
                    setTablePengadaan("");
                    //Add mutasi
                    int lastRow = tablePengadaan.getRowCount()-1;
                    TableModel tableModel = tablePengadaan.getModel();
                    double nominal = obat.getHarga() * pengadaan.getJumlah_obat();
                    Mutasi m = new Mutasi(0, Integer.parseInt(tableModel.getValueAt(lastRow, 9).toString()),
                        nominal,
                        mutasiControl.getSaldo()-nominal, //ambil saldo yang terbaru
                        "Pegadaan obat "+obat.getNama()+" sebesar "+pengadaan.getJumlah_obat(),
                        "Pengeluaran",
                        sqlDateTime);
                    mutasiControl.insertDataMutasi(m);
                    clearAll();
                    setObatDropdown();
                    setSupplierDropdown();
                    setTablePengadaan("");
                }else{
                    JOptionPane.showConfirmDialog(this, "Jumlah obat harus angka diatas 0","Error",JOptionPane.DEFAULT_OPTION);
                }

            }catch(NumberFormatException e){
                JOptionPane.showConfirmDialog(this, "Jumlah obat harus angka diatas 0","Error",JOptionPane.DEFAULT_OPTION);
            }

        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void totalHargaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalHargaTxtActionPerformed

    private void saldoKlinikTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoKlinikTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoKlinikTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Obat> ObatDropdown;
    private javax.swing.JTabbedPane ObatTab;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField emailSupplier;
    private javax.swing.JTextField hargaObat;
    private javax.swing.JPanel inputTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jumlahObat;
    private javax.swing.JTextField namaObat;
    private javax.swing.JTextField namaSupplier;
    private javax.swing.JPanel newObatTab;
    private javax.swing.JPanel newSupplierTab;
    private javax.swing.JTextField notelpSupplier;
    private AdminDashboard.ObatPanel obatPanel1;
    private javax.swing.JPanel oldObatTab;
    private javax.swing.JPanel oldSupplierTab;
    private javax.swing.JTabbedPane pengadaanTab;
    private javax.swing.JPanel riwayatTab;
    private javax.swing.JTextField saldoKlinikTxt;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JComboBox<Supplier> supplierDropDown;
    private javax.swing.JTabbedPane supplierTab;
    private KasirDashboard.TableCustom tablePengadaan;
    private javax.swing.JTextField totalHargaTxt;
    // End of variables declaration//GEN-END:variables
    private void setTablePengadaan(String query) {
        tablePengadaan.setModel(pengadaanControl.getTableSuplier(query));
        UtilTable.tableResizeColumnWidth(tablePengadaan);
    }

    private void setObatDropdown() {
        ObatDropdown.removeAllItems();
        listObat = obatControl.showListObat("");
        
        for(int i=1;i<listObat.size();i++){
            ObatDropdown.addItem(listObat.get(i));
        }
    }

    private void setSupplierDropdown() {
        supplierDropDown.removeAllItems();
        listSupplier = supplierControl.getListSupplier("");
       
        for(int i=0;i<listSupplier.size();i++){
            supplierDropDown.addItem(listSupplier.get(i));
        } 
    }

    private Supplier getSupplier(int selectedTab) {
        Supplier s = null;
        if(selectedTab==0){
            selectedIndexSupplier = supplierDropDown.getSelectedIndex();
            s = listSupplier.get(selectedIndexSupplier);
        }else{
            if(supplierControl.searchSupplier(namaSupplier.getText())!=null
                    || supplierControl.searchSupplier(notelpSupplier.getText())!=null
                    || supplierControl.searchSupplier(emailSupplier.getText())!=null
              ){
                JOptionPane.showConfirmDialog(this, "Supplier sudah terdaftar","Warning",JOptionPane.DEFAULT_OPTION);
                return null;
            }
            try{
                inputKosongExceptionSupplier();
                s = new Supplier(namaSupplier.getText(), notelpSupplier.getText(), emailSupplier.getText());
                supplierControl.insertDataSupplier(s);
                s = supplierControl.searchSupplier(namaSupplier.getText());
            }catch(InputKosongException e){
                JOptionPane.showMessageDialog(this, e.message());
            }
            
        }
        return s;
    }

    private Obat getObat(int selectedTab) {
        Obat o = null;
        if(selectedTab==0){
            selectedIndexObat = ObatDropdown.getSelectedIndex()+1;//karena di database ada data 1 obat tidak ada
            o = listObat.get(selectedIndexObat);
        }else{
            if(obatControl.searchObat(namaObat.getText())!=null){
                JOptionPane.showConfirmDialog(this, "Obat sudah terdaftar","Warning",JOptionPane.DEFAULT_OPTION);
                return null;
            }
            try{
                inputKosongExceptionObat();
                if(Double.parseDouble(hargaObat.getText())>0){
                    o = new Obat(namaObat.getText(), Double.parseDouble(hargaObat.getText()), 0);
                    obatControl.insertDataObat(o);
                    o = obatControl.searchObat(namaObat.getText()); 
                }
            }catch(InputKosongException e){
                JOptionPane.showMessageDialog(this, e.message());
            }catch(NumberFormatException nfe){
                JOptionPane.showConfirmDialog(this, "Harga obat harus angka diatas 0","Error",JOptionPane.DEFAULT_OPTION);
            }
        }
        return o;
    }

    private void inputKosongExceptionSupplier() throws InputKosongException{
        if(namaSupplier.getText().isEmpty() || notelpSupplier.getText().isEmpty() || emailSupplier.getText().isEmpty()){
            throw new InputKosongException();
        }
    }

    private void inputKosongExceptionObat() throws InputKosongException{
        if(namaObat.getText().isEmpty()){
            throw new InputKosongException();
        }
    }

    private void setListener() {
        searchTxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setTablePengadaan(searchTxt.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setTablePengadaan(searchTxt.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setTablePengadaan(searchTxt.getText());
            }
        });
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkFields();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkFields();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkFields();
            }

            private void checkFields() {
                updateTotalHarga();
            }
        };
        namaObat.getDocument().addDocumentListener(docListener);
        hargaObat.getDocument().addDocumentListener(docListener);
        namaSupplier.getDocument().addDocumentListener(docListener);
        notelpSupplier.getDocument().addDocumentListener(docListener);
        emailSupplier.getDocument().addDocumentListener(docListener);
        
        jumlahObat.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int value = (int) jumlahObat.getValue();
                if(value<0){
                    jumlahObat.setValue(0);
                }
                updateTotalHarga();
            }
        });
        
        ObatDropdown.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateTotalHarga();
            }
        });
        
        ObatTab.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                updateTotalHarga();
            }
        });
        supplierTab.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                updateTotalHarga();
            }
        });
        pengadaanTab.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                refreshData();
            }
        });
    }
    
    private void updateTotalHarga(){
        
        try{
            inputKosongException();
            int jumlah = (int)jumlahObat.getValue();
            if(ObatTab.getSelectedIndex()==1){
                double harga = Double.parseDouble(hargaObat.getText());
                totalHargaTxt.setText("Rp. "+jumlah*harga);
            }else{
                Obat obat = (Obat) ObatDropdown.getSelectedItem();
                totalHargaTxt.setText("Rp. "+jumlah*obat.getHarga());
            }
            double totalHarga = Double.parseDouble(totalHargaTxt.getText().substring(4));
            double saldoKlinik = Double.parseDouble(saldoKlinikTxt.getText().substring(4));
            addBtn.setEnabled(saldoKlinik>=totalHarga&&totalHarga!=0);
        }catch(InputKosongException e){
            System.out.println(e.message());
            totalHargaTxt.setText("Rp. 0.0");
            addBtn.setEnabled(false);
        }catch(NumberFormatException nfe){
            System.out.println(nfe.getMessage());
            totalHargaTxt.setText("Rp. 0.0");
            addBtn.setEnabled(false);
        }catch(Exception ex){
            System.out.println(ex.getMessage());
            totalHargaTxt.setText("Rp. 0.0");
            addBtn.setEnabled(false);
        }
    }

    private void inputKosongException() throws InputKosongException{
        if(ObatTab.getSelectedIndex()==1 && supplierTab.getSelectedIndex()==1){
            if(namaObat.getText().isEmpty()
                    || hargaObat.getText().isEmpty()
                    || namaSupplier.getText().isEmpty()
                    || notelpSupplier.getText().isEmpty()
                    || emailSupplier.getText().isEmpty()){
                throw new InputKosongException();
            }
        }else if(ObatTab.getSelectedIndex()==1){
            if(namaObat.getText().isEmpty()
                    || hargaObat.getText().isEmpty()){
                throw new InputKosongException();
            }
        }else if(supplierTab.getSelectedIndex()==1){
            if(namaSupplier.getText().isEmpty()
                    || notelpSupplier.getText().isEmpty()
                    || emailSupplier.getText().isEmpty()){
                throw new InputKosongException();
            }
        }
    }

    private void clearAll() {
        jumlahObat.setValue(0);
        namaSupplier.setText("");
        notelpSupplier.setText("");
        emailSupplier.setText("");
        namaObat.setText("");
        hargaObat.setText("");
        saldoKlinikTxt.setText("Rp. "+mutasiControl.getSaldo());
    }

    @Override
    public void refreshData() {
        setTablePengadaan("");
        setObatDropdown();
        setSupplierDropdown();
        searchTxt.setText("");
        obatPanel1.refreshData();
    }
    private void setBorderandFocus(JComponent comp){
        comp.putClientProperty(FlatClientProperties.STYLE, ""
                +"borderWidth:1;"
                + "focusWidth:0");
    }
}
